//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "qq_agent_turns"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub turn_id: u64,
    pub bot_account_id: u64,
    pub qq_group_id: i64,
    pub trigger_message_id: u64,
    pub response_message_id: Option<u64>,
    pub trigger_type: String,
    pub qq_user_id: Option<i64>,
    pub internal_user_id: Option<u64>,
    pub prompt_version: Option<String>,
    pub model_name: Option<String>,
    pub reasoning_enabled: Option<i8>,
    pub input_token_count: Option<u32>,
    pub output_token_count: Option<u32>,
    pub latency_ms: Option<u32>,
    pub status: String,
    pub error_message: Option<String>,
    pub trace_id: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    TurnId,
    BotAccountId,
    QqGroupId,
    TriggerMessageId,
    ResponseMessageId,
    TriggerType,
    QqUserId,
    InternalUserId,
    PromptVersion,
    ModelName,
    ReasoningEnabled,
    InputTokenCount,
    OutputTokenCount,
    LatencyMs,
    Status,
    ErrorMessage,
    TraceId,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    TurnId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    QqBotAccounts,
    QqGroupMessages2,
    QqGroupMessages1,
    QqMessageOutbox,
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::TurnId => ColumnType::BigUnsigned.def(),
            Self::BotAccountId => ColumnType::BigUnsigned.def(),
            Self::QqGroupId => ColumnType::BigInteger.def(),
            Self::TriggerMessageId => ColumnType::BigUnsigned.def(),
            Self::ResponseMessageId => ColumnType::BigUnsigned.def().null(),
            Self::TriggerType => ColumnType::String(StringLen::N(10u32)).def(),
            Self::QqUserId => ColumnType::BigInteger.def().null(),
            Self::InternalUserId => ColumnType::BigUnsigned.def().null(),
            Self::PromptVersion => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::ModelName => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::ReasoningEnabled => ColumnType::TinyInteger.def().null(),
            Self::InputTokenCount => ColumnType::Unsigned.def().null(),
            Self::OutputTokenCount => ColumnType::Unsigned.def().null(),
            Self::LatencyMs => ColumnType::Unsigned.def().null(),
            Self::Status => ColumnType::String(StringLen::N(15u32)).def(),
            Self::ErrorMessage => ColumnType::Text.def().null(),
            Self::TraceId => ColumnType::String(StringLen::N(64u32))
                .def()
                .null()
                .unique(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::QqBotAccounts => Entity::belongs_to(super::qq_bot_accounts::Entity)
                .from(Column::BotAccountId)
                .to(super::qq_bot_accounts::Column::BotAccountId)
                .into(),
            Self::QqGroupMessages2 => Entity::belongs_to(super::qq_group_messages::Entity)
                .from(Column::TriggerMessageId)
                .to(super::qq_group_messages::Column::Id)
                .into(),
            Self::QqGroupMessages1 => Entity::belongs_to(super::qq_group_messages::Entity)
                .from(Column::ResponseMessageId)
                .to(super::qq_group_messages::Column::Id)
                .into(),
            Self::QqMessageOutbox => Entity::has_many(super::qq_message_outbox::Entity).into(),
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::InternalUserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::qq_bot_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqBotAccounts.def()
    }
}

impl Related<super::qq_message_outbox::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqMessageOutbox.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
