//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "qq_external_users"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub qq_user_id: i64,
    pub internal_user_id: Option<u64>,
    pub nickname: Option<String>,
    pub avatar_url: Option<String>,
    pub last_seen_at: Option<i64>,
    pub memory_enabled: i8,
    pub persona_enabled: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    QqUserId,
    InternalUserId,
    Nickname,
    AvatarUrl,
    LastSeenAt,
    MemoryEnabled,
    PersonaEnabled,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    QqUserId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    QqGroupMembers,
    QqGroupMessages,
    QqRelationships,
    QqUserProfiles,
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::QqUserId => ColumnType::BigInteger.def(),
            Self::InternalUserId => ColumnType::BigUnsigned.def().null(),
            Self::Nickname => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::AvatarUrl => ColumnType::String(StringLen::N(512u32)).def().null(),
            Self::LastSeenAt => ColumnType::BigInteger.def().null(),
            Self::MemoryEnabled => ColumnType::TinyInteger.def(),
            Self::PersonaEnabled => ColumnType::TinyInteger.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::QqGroupMembers => Entity::has_many(super::qq_group_members::Entity).into(),
            Self::QqGroupMessages => Entity::has_many(super::qq_group_messages::Entity).into(),
            Self::QqRelationships => Entity::has_many(super::qq_relationships::Entity).into(),
            Self::QqUserProfiles => Entity::has_one(super::qq_user_profiles::Entity).into(),
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::InternalUserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::qq_group_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqGroupMembers.def()
    }
}

impl Related<super::qq_group_messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqGroupMessages.def()
    }
}

impl Related<super::qq_relationships::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqRelationships.def()
    }
}

impl Related<super::qq_user_profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqUserProfiles.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::qq_groups::Entity> for Entity {
    fn to() -> RelationDef {
        super::qq_group_members::Relation::QqGroups.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::qq_group_members::Relation::QqExternalUsers
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
