//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "qq_group_memories"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub group_memory_id: u64,
    pub qq_group_id: i64,
    pub memory_key: Option<String>,
    pub canonical_form: Option<String>,
    pub memory_type: String,
    pub content: String,
    pub confidence: f64,
    pub salience: f64,
    pub source_message_id: Option<u64>,
    pub reinforce_count: u32,
    pub status: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    GroupMemoryId,
    QqGroupId,
    MemoryKey,
    CanonicalForm,
    MemoryType,
    Content,
    Confidence,
    Salience,
    SourceMessageId,
    ReinforceCount,
    Status,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    GroupMemoryId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    QqGroupMessages,
    QqGroups,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::GroupMemoryId => ColumnType::BigUnsigned.def(),
            Self::QqGroupId => ColumnType::BigInteger.def(),
            Self::MemoryKey => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::CanonicalForm => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::MemoryType => ColumnType::String(StringLen::N(30u32)).def(),
            Self::Content => ColumnType::Text.def(),
            Self::Confidence => ColumnType::Double.def(),
            Self::Salience => ColumnType::Double.def(),
            Self::SourceMessageId => ColumnType::BigUnsigned.def().null(),
            Self::ReinforceCount => ColumnType::Unsigned.def(),
            Self::Status => ColumnType::TinyInteger.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::QqGroupMessages => Entity::belongs_to(super::qq_group_messages::Entity)
                .from(Column::SourceMessageId)
                .to(super::qq_group_messages::Column::Id)
                .into(),
            Self::QqGroups => Entity::belongs_to(super::qq_groups::Entity)
                .from(Column::QqGroupId)
                .to(super::qq_groups::Column::QqGroupId)
                .into(),
        }
    }
}

impl Related<super::qq_group_messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqGroupMessages.def()
    }
}

impl Related<super::qq_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqGroups.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
