//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "qq_user_profiles"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub qq_user_id: i64,
    pub interest_tags: Option<Json>,
    pub active_hours: Option<Json>,
    pub speaking_style: Option<String>,
    pub topic_frequency: Option<Json>,
    pub total_messages: u32,
    pub avg_message_length: f64,
    pub emoji_usage_rate: f64,
    pub first_seen_at: Option<i64>,
    pub last_summary_at: Option<i64>,
    pub raw_profile: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    QqUserId,
    InterestTags,
    ActiveHours,
    SpeakingStyle,
    TopicFrequency,
    TotalMessages,
    AvgMessageLength,
    EmojiUsageRate,
    FirstSeenAt,
    LastSummaryAt,
    RawProfile,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    QqUserId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    QqExternalUsers,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::QqUserId => ColumnType::BigInteger.def(),
            Self::InterestTags => ColumnType::Json.def().null(),
            Self::ActiveHours => ColumnType::Json.def().null(),
            Self::SpeakingStyle => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::TopicFrequency => ColumnType::Json.def().null(),
            Self::TotalMessages => ColumnType::Unsigned.def(),
            Self::AvgMessageLength => ColumnType::Double.def(),
            Self::EmojiUsageRate => ColumnType::Double.def(),
            Self::FirstSeenAt => ColumnType::BigInteger.def().null(),
            Self::LastSummaryAt => ColumnType::BigInteger.def().null(),
            Self::RawProfile => ColumnType::Text.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::QqExternalUsers => Entity::belongs_to(super::qq_external_users::Entity)
                .from(Column::QqUserId)
                .to(super::qq_external_users::Column::QqUserId)
                .into(),
        }
    }
}

impl Related<super::qq_external_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqExternalUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
