//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "users"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: u64,
    pub username: String,
    pub password: String,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub avatar: Option<Vec<u8>>,
    pub nickname: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub last_login_at: Option<DateTime>,
    pub status: i8,
    pub role: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Username,
    Password,
    Email,
    Phone,
    Avatar,
    Nickname,
    CreatedAt,
    UpdatedAt,
    LastLoginAt,
    Status,
    Role,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    AgentEvents,
    CommunityComments,
    CommunityPosts,
    ContentLikes,
    ConversationSummaries,
    Conversations,
    DepressionAssessments,
    KnowledgeDocuments,
    PostConversationRiskAudits,
    QqAgentTurns,
    QqExternalUsers,
    RefreshTokens,
    StoredObjects,
    UserContextVersions,
    UserDiaries,
    UserKnowledgeFavorites,
    UserMemories,
    UserPersonaSnapshots,
    UserProfiles,
    VectorIndexRecords,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigUnsigned.def(),
            Self::Username => ColumnType::String(StringLen::N(50u32)).def().unique(),
            Self::Password => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Email => ColumnType::String(StringLen::N(100u32))
                .def()
                .null()
                .unique(),
            Self::Phone => ColumnType::String(StringLen::N(20u32))
                .def()
                .null()
                .unique(),
            Self::Avatar => ColumnType::Binary(255u32).def().null(),
            Self::Nickname => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::LastLoginAt => ColumnType::DateTime.def().null(),
            Self::Status => ColumnType::TinyInteger.def(),
            Self::Role => ColumnType::String(StringLen::N(32u32)).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::AgentEvents => Entity::has_many(super::agent_events::Entity).into(),
            Self::CommunityComments => Entity::has_many(super::community_comments::Entity).into(),
            Self::CommunityPosts => Entity::has_many(super::community_posts::Entity).into(),
            Self::ContentLikes => Entity::has_many(super::content_likes::Entity).into(),
            Self::ConversationSummaries => {
                Entity::has_many(super::conversation_summaries::Entity).into()
            }
            Self::Conversations => Entity::has_one(super::conversations::Entity).into(),
            Self::DepressionAssessments => {
                Entity::has_many(super::depression_assessments::Entity).into()
            }
            Self::KnowledgeDocuments => Entity::has_many(super::knowledge_documents::Entity).into(),
            Self::PostConversationRiskAudits => {
                Entity::has_many(super::post_conversation_risk_audits::Entity).into()
            }
            Self::QqAgentTurns => Entity::has_many(super::qq_agent_turns::Entity).into(),
            Self::QqExternalUsers => Entity::has_many(super::qq_external_users::Entity).into(),
            Self::RefreshTokens => Entity::has_many(super::refresh_tokens::Entity).into(),
            Self::StoredObjects => Entity::has_many(super::stored_objects::Entity).into(),
            Self::UserContextVersions => {
                Entity::has_one(super::user_context_versions::Entity).into()
            }
            Self::UserDiaries => Entity::has_many(super::user_diaries::Entity).into(),
            Self::UserKnowledgeFavorites => {
                Entity::has_many(super::user_knowledge_favorites::Entity).into()
            }
            Self::UserMemories => Entity::has_many(super::user_memories::Entity).into(),
            Self::UserPersonaSnapshots => {
                Entity::has_many(super::user_persona_snapshots::Entity).into()
            }
            Self::UserProfiles => Entity::has_one(super::user_profiles::Entity).into(),
            Self::VectorIndexRecords => {
                Entity::has_many(super::vector_index_records::Entity).into()
            }
        }
    }
}

impl Related<super::agent_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentEvents.def()
    }
}

impl Related<super::community_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommunityComments.def()
    }
}

impl Related<super::community_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommunityPosts.def()
    }
}

impl Related<super::content_likes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentLikes.def()
    }
}

impl Related<super::conversation_summaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConversationSummaries.def()
    }
}

impl Related<super::conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Conversations.def()
    }
}

impl Related<super::depression_assessments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DepressionAssessments.def()
    }
}

impl Related<super::knowledge_documents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeDocuments.def()
    }
}

impl Related<super::post_conversation_risk_audits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostConversationRiskAudits.def()
    }
}

impl Related<super::qq_agent_turns::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqAgentTurns.def()
    }
}

impl Related<super::qq_external_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqExternalUsers.def()
    }
}

impl Related<super::refresh_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefreshTokens.def()
    }
}

impl Related<super::stored_objects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StoredObjects.def()
    }
}

impl Related<super::user_context_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserContextVersions.def()
    }
}

impl Related<super::user_diaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserDiaries.def()
    }
}

impl Related<super::user_knowledge_favorites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserKnowledgeFavorites.def()
    }
}

impl Related<super::user_memories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMemories.def()
    }
}

impl Related<super::user_persona_snapshots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPersonaSnapshots.def()
    }
}

impl Related<super::user_profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserProfiles.def()
    }
}

impl Related<super::vector_index_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VectorIndexRecords.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
