//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "community_comments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub comment_id: u64,
    pub post_id: u64,
    pub user_id: u64,
    pub parent_comment_id: Option<u64>,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub attachments: Option<Json>,
    pub likes_count: u32,
    pub status: i8,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentCommentId",
        to = "Column::CommentId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SelfRef,
    #[sea_orm(
        belongs_to = "super::community_posts::Entity",
        from = "Column::PostId",
        to = "super::community_posts::Column::PostId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CommunityPosts,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::community_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommunityPosts.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
