//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "community_post_media")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub media_id: u64,
    pub post_id: u64,
    pub media_type: String,
    pub mime_type: String,
    #[sea_orm(ignore, column_type = "custom(\"longblob\")", select_as = "text")]
    pub media_data: String,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::community_posts::Entity",
        from = "Column::PostId",
        to = "super::community_posts::Column::PostId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CommunityPosts,
}

impl Related<super::community_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommunityPosts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
