//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "community_comments"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub comment_id: u64,
    pub post_id: u64,
    pub user_id: u64,
    pub parent_comment_id: Option<u64>,
    pub content: String,
    pub attachments: Option<Json>,
    pub likes_count: u32,
    pub status: i8,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    CommentId,
    PostId,
    UserId,
    ParentCommentId,
    Content,
    Attachments,
    LikesCount,
    Status,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    CommentId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    SelfRef,
    CommunityPosts,
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::CommentId => ColumnType::BigUnsigned.def(),
            Self::PostId => ColumnType::BigUnsigned.def(),
            Self::UserId => ColumnType::BigUnsigned.def(),
            Self::ParentCommentId => ColumnType::BigUnsigned.def().null(),
            Self::Content => ColumnType::Text.def(),
            Self::Attachments => ColumnType::Json.def().null(),
            Self::LikesCount => ColumnType::Unsigned.def(),
            Self::Status => ColumnType::TinyInteger.def(),
            Self::CreatedAt => ColumnType::Timestamp.def(),
            Self::UpdatedAt => ColumnType::Timestamp.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::SelfRef => Entity::belongs_to(Entity)
                .from(Column::ParentCommentId)
                .to(Column::CommentId)
                .into(),
            Self::CommunityPosts => Entity::belongs_to(super::community_posts::Entity)
                .from(Column::PostId)
                .to(super::community_posts::Column::PostId)
                .into(),
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::UserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::community_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommunityPosts.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
