//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "community_posts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub post_id: u64,
    pub user_id: u64,
    pub title: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub extra_metadata: Option<Json>,
    pub likes_count: u32,
    pub comments_count: u32,
    pub status: i8,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::community_comments::Entity")]
    CommunityComments,
    #[sea_orm(has_many = "super::community_post_media::Entity")]
    CommunityPostMedia,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::community_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommunityComments.def()
    }
}

impl Related<super::community_post_media::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommunityPostMedia.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
