//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "conversation_messages"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: u64,
    pub conversation_id: u64,
    pub sender_role: String,
    pub sender_user_id: Option<u64>,
    pub message_type: String,
    pub content: Json,
    pub token_count: Option<u32>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    ConversationId,
    SenderRole,
    SenderUserId,
    MessageType,
    Content,
    TokenCount,
    CreatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Conversations,
    RiskDetectionResults,
    UserMemories,
    UserMemoryEvidence,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigUnsigned.def(),
            Self::ConversationId => ColumnType::BigUnsigned.def(),
            Self::SenderRole => ColumnType::String(StringLen::N(32u32)).def(),
            Self::SenderUserId => ColumnType::BigUnsigned.def().null(),
            Self::MessageType => ColumnType::String(StringLen::N(32u32)).def(),
            Self::Content => ColumnType::Json.def(),
            Self::TokenCount => ColumnType::Unsigned.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Conversations => Entity::belongs_to(super::conversations::Entity)
                .from(Column::ConversationId)
                .to(super::conversations::Column::Id)
                .into(),
            Self::RiskDetectionResults => {
                Entity::has_many(super::risk_detection_results::Entity).into()
            }
            Self::UserMemories => Entity::has_many(super::user_memories::Entity).into(),
            Self::UserMemoryEvidence => {
                Entity::has_many(super::user_memory_evidence::Entity).into()
            }
        }
    }
}

impl Related<super::conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Conversations.def()
    }
}

impl Related<super::risk_detection_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RiskDetectionResults.def()
    }
}

impl Related<super::user_memories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMemories.def()
    }
}

impl Related<super::user_memory_evidence::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMemoryEvidence.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
