//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "conversations")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: u64,
    pub user_id: u64,
    pub title: Option<String>,
    pub is_title_generated: i8,
    pub last_message_at: Option<DateTimeUtc>,
    pub message_count: u32,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::agent_events::Entity")]
    AgentEvents,
    #[sea_orm(has_many = "super::conversation_messages::Entity")]
    ConversationMessages,
    #[sea_orm(has_many = "super::conversation_summaries::Entity")]
    ConversationSummaries,
    #[sea_orm(has_many = "super::risk_detection_results::Entity")]
    RiskDetectionResults,
    #[sea_orm(has_many = "super::user_memories::Entity")]
    UserMemories,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::agent_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentEvents.def()
    }
}

impl Related<super::conversation_messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConversationMessages.def()
    }
}

impl Related<super::conversation_summaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConversationSummaries.def()
    }
}

impl Related<super::risk_detection_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RiskDetectionResults.def()
    }
}

impl Related<super::user_memories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMemories.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
