//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "conversations"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: u64,
    pub user_id: u64,
    pub title: Option<String>,
    pub is_title_generated: i8,
    pub last_message_at: Option<DateTimeUtc>,
    pub message_count: u32,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    UserId,
    Title,
    IsTitleGenerated,
    LastMessageAt,
    MessageCount,
    CreatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    AgentEvents,
    ConversationMessages,
    ConversationSummaries,
    RiskDetectionResults,
    UserMemories,
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigUnsigned.def(),
            Self::UserId => ColumnType::BigUnsigned.def(),
            Self::Title => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::IsTitleGenerated => ColumnType::TinyInteger.def(),
            Self::LastMessageAt => ColumnType::Timestamp.def().null(),
            Self::MessageCount => ColumnType::Unsigned.def(),
            Self::CreatedAt => ColumnType::Timestamp.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::AgentEvents => Entity::has_many(super::agent_events::Entity).into(),
            Self::ConversationMessages => {
                Entity::has_many(super::conversation_messages::Entity).into()
            }
            Self::ConversationSummaries => {
                Entity::has_many(super::conversation_summaries::Entity).into()
            }
            Self::RiskDetectionResults => {
                Entity::has_many(super::risk_detection_results::Entity).into()
            }
            Self::UserMemories => Entity::has_many(super::user_memories::Entity).into(),
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::UserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::agent_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentEvents.def()
    }
}

impl Related<super::conversation_messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConversationMessages.def()
    }
}

impl Related<super::conversation_summaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConversationSummaries.def()
    }
}

impl Related<super::risk_detection_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RiskDetectionResults.def()
    }
}

impl Related<super::user_memories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMemories.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
