//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "depression_scales"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub scale_id: u16,
    pub scale_name: String,
    pub scale_description: Option<String>,
    pub min_score: i16,
    pub max_score: i16,
    pub severity_ranges: Json,
    pub questions: Json,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    ScaleId,
    ScaleName,
    ScaleDescription,
    MinScore,
    MaxScore,
    SeverityRanges,
    Questions,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    ScaleId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u16;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    DepressionAssessments,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::ScaleId => ColumnType::SmallUnsigned.def(),
            Self::ScaleName => ColumnType::String(StringLen::N(50u32)).def().unique(),
            Self::ScaleDescription => ColumnType::Text.def().null(),
            Self::MinScore => ColumnType::SmallInteger.def(),
            Self::MaxScore => ColumnType::SmallInteger.def(),
            Self::SeverityRanges => ColumnType::Json.def(),
            Self::Questions => ColumnType::Json.def(),
            Self::CreatedAt => ColumnType::Timestamp.def().null(),
            Self::UpdatedAt => ColumnType::Timestamp.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::DepressionAssessments => {
                Entity::has_many(super::depression_assessments::Entity).into()
            }
        }
    }
}

impl Related<super::depression_assessments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DepressionAssessments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
