//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "depression_assessments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub assessment_id: u64,
    pub user_id: u64,
    pub scale_id: u16,
    pub assessment_date: Date,
    pub answers: Json,
    pub total_score: i16,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::depression_scales::Entity",
        from = "Column::ScaleId",
        to = "super::depression_scales::Column::ScaleId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DepressionScales,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::depression_scales::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DepressionScales.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
