//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "depression_scales")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub scale_id: u16,
    #[sea_orm(unique)]
    pub scale_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub scale_description: Option<String>,
    pub min_score: i16,
    pub max_score: i16,
    pub severity_ranges: Json,
    pub questions: Json,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::depression_assessments::Entity")]
    DepressionAssessments,
}

impl Related<super::depression_assessments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DepressionAssessments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
