//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "domain_event_outbox"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: u64,
    pub event_key: String,
    pub event_type: String,
    pub aggregate_type: String,
    pub aggregate_id: u64,
    pub payload: Json,
    pub status: String,
    pub retry_count: u32,
    pub max_retries: u32,
    pub next_retry_at: Option<DateTime>,
    pub locked_by: Option<String>,
    pub locked_until: Option<DateTime>,
    pub last_error: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub published_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    EventKey,
    EventType,
    AggregateType,
    AggregateId,
    Payload,
    Status,
    RetryCount,
    MaxRetries,
    NextRetryAt,
    LockedBy,
    LockedUntil,
    LastError,
    CreatedAt,
    UpdatedAt,
    PublishedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigUnsigned.def(),
            Self::EventKey => ColumnType::Char(Some(64u32)).def().unique(),
            Self::EventType => ColumnType::String(StringLen::N(128u32)).def(),
            Self::AggregateType => ColumnType::String(StringLen::N(64u32)).def(),
            Self::AggregateId => ColumnType::BigUnsigned.def(),
            Self::Payload => ColumnType::Json.def(),
            Self::Status => ColumnType::String(StringLen::N(32u32)).def(),
            Self::RetryCount => ColumnType::Unsigned.def(),
            Self::MaxRetries => ColumnType::Unsigned.def(),
            Self::NextRetryAt => ColumnType::DateTime.def().null(),
            Self::LockedBy => ColumnType::String(StringLen::N(128u32)).def().null(),
            Self::LockedUntil => ColumnType::DateTime.def().null(),
            Self::LastError => ColumnType::Text.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::PublishedAt => ColumnType::DateTime.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
