//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "knowledge_embeddings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub embedding_id: u64,
    #[sea_orm(unique_key = "uk_knowledge_embeddings_chunk_model")]
    pub chunk_id: u64,
    #[sea_orm(unique_key = "uk_knowledge_embeddings_chunk_model")]
    pub provider: String,
    #[sea_orm(unique_key = "uk_knowledge_embeddings_chunk_model")]
    pub model: String,
    pub dimension: u32,
    pub embedding_json: Json,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::knowledge_chunks::Entity",
        from = "Column::ChunkId",
        to = "super::knowledge_chunks::Column::ChunkId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    KnowledgeChunks,
}

impl Related<super::knowledge_chunks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeChunks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
