//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "knowledge_chunks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub chunk_id: u64,
    #[sea_orm(unique_key = "uk_knowledge_chunks_doc_idx")]
    pub document_id: u64,
    #[sea_orm(unique_key = "uk_knowledge_chunks_doc_idx")]
    pub chunk_index: u32,
    pub char_start: Option<u32>,
    pub char_end: Option<u32>,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub content_hash: Option<String>,
    pub token_count: Option<u32>,
    pub metadata: Option<Json>,
    pub status: i8,
    pub created_at: DateTime,
    #[sea_orm(unique)]
    pub vector_id: Option<String>,
    pub embedding_provider: Option<String>,
    pub embedding_model: Option<String>,
    pub embedding_dimension: Option<u32>,
    pub indexed_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::knowledge_documents::Entity",
        from = "Column::DocumentId",
        to = "super::knowledge_documents::Column::DocumentId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    KnowledgeDocuments,
    #[sea_orm(has_many = "super::knowledge_embeddings::Entity")]
    KnowledgeEmbeddings,
}

impl Related<super::knowledge_documents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeDocuments.def()
    }
}

impl Related<super::knowledge_embeddings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeEmbeddings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
