//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "knowledge_documents")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub document_id: u64,
    #[sea_orm(unique_key = "uk_knowledge_documents_source")]
    pub source_type: String,
    #[sea_orm(unique_key = "uk_knowledge_documents_source")]
    pub source_id: Option<u64>,
    pub title: Option<String>,
    pub content_hash: String,
    pub metadata: Option<Json>,
    pub status: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::knowledge_chunks::Entity")]
    KnowledgeChunks,
}

impl Related<super::knowledge_chunks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeChunks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
