//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "knowledge_ingestion_runs"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub id: u64,
    pub source_id: u64,
    pub source_url_id: Option<u64>,
    pub crawl_job_id: Option<u64>,
    pub page_id: u64,
    pub content_hash: String,
    pub content_key: String,
    pub run_key: String,
    pub version_key: String,
    pub status: String,
    pub stage: String,
    pub llm_provider: Option<String>,
    pub llm_model: Option<String>,
    pub llm_prompt_version: Option<String>,
    pub llm_input_tokens: Option<u32>,
    pub llm_output_tokens: Option<u32>,
    pub chunker_version: Option<String>,
    pub embedding_provider: Option<String>,
    pub embedding_model: Option<String>,
    pub embedding_dimension: Option<u32>,
    pub quality_score: Option<f64>,
    pub quality_result: Option<Json>,
    pub risk_flags: Option<Json>,
    pub should_publish: Option<i8>,
    pub last_error: Option<String>,
    pub retry_count: u32,
    pub started_at: Option<DateTime>,
    pub finished_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub fetched_body_text: Option<String>,
    pub clean_text: Option<String>,
    pub distilled_json: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    SourceId,
    SourceUrlId,
    CrawlJobId,
    PageId,
    ContentHash,
    ContentKey,
    RunKey,
    VersionKey,
    Status,
    Stage,
    LlmProvider,
    LlmModel,
    LlmPromptVersion,
    LlmInputTokens,
    LlmOutputTokens,
    ChunkerVersion,
    EmbeddingProvider,
    EmbeddingModel,
    EmbeddingDimension,
    QualityScore,
    QualityResult,
    RiskFlags,
    ShouldPublish,
    LastError,
    RetryCount,
    StartedAt,
    FinishedAt,
    CreatedAt,
    UpdatedAt,
    FetchedBodyText,
    CleanText,
    DistilledJson,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    KnowledgeChunkManifests,
    KnowledgePublishRecords,
    KnowledgeVectorManifests,
    WebCrawlJobs,
    WebIngestionAuditLogs,
    WebPages,
    WebSourceUrls,
    WebSources,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigUnsigned.def(),
            Self::SourceId => ColumnType::BigUnsigned.def(),
            Self::SourceUrlId => ColumnType::BigUnsigned.def().null(),
            Self::CrawlJobId => ColumnType::BigUnsigned.def().null(),
            Self::PageId => ColumnType::BigUnsigned.def(),
            Self::ContentHash => ColumnType::Char(Some(64u32)).def(),
            Self::ContentKey => ColumnType::Char(Some(64u32)).def(),
            Self::RunKey => ColumnType::Char(Some(64u32)).def().unique(),
            Self::VersionKey => ColumnType::Char(Some(64u32)).def().unique(),
            Self::Status => ColumnType::String(StringLen::N(32u32)).def(),
            Self::Stage => ColumnType::String(StringLen::N(32u32)).def(),
            Self::LlmProvider => ColumnType::String(StringLen::N(64u32)).def().null(),
            Self::LlmModel => ColumnType::String(StringLen::N(128u32)).def().null(),
            Self::LlmPromptVersion => ColumnType::String(StringLen::N(64u32)).def().null(),
            Self::LlmInputTokens => ColumnType::Unsigned.def().null(),
            Self::LlmOutputTokens => ColumnType::Unsigned.def().null(),
            Self::ChunkerVersion => ColumnType::String(StringLen::N(64u32)).def().null(),
            Self::EmbeddingProvider => ColumnType::String(StringLen::N(64u32)).def().null(),
            Self::EmbeddingModel => ColumnType::String(StringLen::N(128u32)).def().null(),
            Self::EmbeddingDimension => ColumnType::Unsigned.def().null(),
            Self::QualityScore => ColumnType::Double.def().null(),
            Self::QualityResult => ColumnType::Json.def().null(),
            Self::RiskFlags => ColumnType::Json.def().null(),
            Self::ShouldPublish => ColumnType::TinyInteger.def().null(),
            Self::LastError => ColumnType::Text.def().null(),
            Self::RetryCount => ColumnType::Unsigned.def(),
            Self::StartedAt => ColumnType::DateTime.def().null(),
            Self::FinishedAt => ColumnType::DateTime.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::FetchedBodyText => ColumnType::Text.def().null(),
            Self::CleanText => ColumnType::Text.def().null(),
            Self::DistilledJson => ColumnType::Json.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::KnowledgeChunkManifests => {
                Entity::has_many(super::knowledge_chunk_manifests::Entity).into()
            }
            Self::KnowledgePublishRecords => {
                Entity::has_many(super::knowledge_publish_records::Entity).into()
            }
            Self::KnowledgeVectorManifests => {
                Entity::has_many(super::knowledge_vector_manifests::Entity).into()
            }
            Self::WebCrawlJobs => Entity::belongs_to(super::web_crawl_jobs::Entity)
                .from(Column::CrawlJobId)
                .to(super::web_crawl_jobs::Column::Id)
                .into(),
            Self::WebIngestionAuditLogs => {
                Entity::has_many(super::web_ingestion_audit_logs::Entity).into()
            }
            Self::WebPages => Entity::belongs_to(super::web_pages::Entity)
                .from(Column::PageId)
                .to(super::web_pages::Column::Id)
                .into(),
            Self::WebSourceUrls => Entity::belongs_to(super::web_source_urls::Entity)
                .from(Column::SourceUrlId)
                .to(super::web_source_urls::Column::Id)
                .into(),
            Self::WebSources => Entity::belongs_to(super::web_sources::Entity)
                .from(Column::SourceId)
                .to(super::web_sources::Column::Id)
                .into(),
        }
    }
}

impl Related<super::knowledge_chunk_manifests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeChunkManifests.def()
    }
}

impl Related<super::knowledge_publish_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgePublishRecords.def()
    }
}

impl Related<super::knowledge_vector_manifests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeVectorManifests.def()
    }
}

impl Related<super::web_crawl_jobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebCrawlJobs.def()
    }
}

impl Related<super::web_ingestion_audit_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebIngestionAuditLogs.def()
    }
}

impl Related<super::web_pages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebPages.def()
    }
}

impl Related<super::web_source_urls::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebSourceUrls.def()
    }
}

impl Related<super::web_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebSources.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
