//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "knowledge_documents"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub document_id: u64,
    pub source_type: String,
    pub source_id: Option<u64>,
    pub owner_user_id: Option<u64>,
    pub visibility: String,
    pub title: Option<String>,
    pub content_hash: String,
    pub source_version: Option<String>,
    pub source_updated_at: Option<DateTime>,
    pub metadata: Option<Json>,
    pub status: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    DocumentId,
    SourceType,
    SourceId,
    OwnerUserId,
    Visibility,
    Title,
    ContentHash,
    SourceVersion,
    SourceUpdatedAt,
    Metadata,
    Status,
    CreatedAt,
    UpdatedAt,
    DeletedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    DocumentId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    KnowledgeChunkManifests,
    KnowledgeChunks,
    KnowledgePublishRecords,
    KnowledgeVectorManifests,
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::DocumentId => ColumnType::BigUnsigned.def(),
            Self::SourceType => ColumnType::String(StringLen::N(64u32)).def(),
            Self::SourceId => ColumnType::BigUnsigned.def().null(),
            Self::OwnerUserId => ColumnType::BigUnsigned.def().null(),
            Self::Visibility => ColumnType::String(StringLen::N(32u32)).def(),
            Self::Title => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::ContentHash => ColumnType::Char(Some(64u32)).def(),
            Self::SourceVersion => ColumnType::String(StringLen::N(128u32)).def().null(),
            Self::SourceUpdatedAt => ColumnType::DateTime.def().null(),
            Self::Metadata => ColumnType::Json.def().null(),
            Self::Status => ColumnType::TinyInteger.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::DeletedAt => ColumnType::DateTime.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::KnowledgeChunkManifests => {
                Entity::has_many(super::knowledge_chunk_manifests::Entity).into()
            }
            Self::KnowledgeChunks => Entity::has_many(super::knowledge_chunks::Entity).into(),
            Self::KnowledgePublishRecords => {
                Entity::has_many(super::knowledge_publish_records::Entity).into()
            }
            Self::KnowledgeVectorManifests => {
                Entity::has_many(super::knowledge_vector_manifests::Entity).into()
            }
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::OwnerUserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::knowledge_chunk_manifests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeChunkManifests.def()
    }
}

impl Related<super::knowledge_chunks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeChunks.def()
    }
}

impl Related<super::knowledge_publish_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgePublishRecords.def()
    }
}

impl Related<super::knowledge_vector_manifests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeVectorManifests.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
