//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "knowledge_publish_records"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: u64,
    pub source_id: u64,
    pub page_id: u64,
    pub run_id: u64,
    pub document_id: u64,
    pub version_key: String,
    pub content_hash: String,
    pub publish_status: String,
    pub active: i8,
    pub activated_at: Option<DateTime>,
    pub superseded_at: Option<DateTime>,
    pub superseded_by_record_id: Option<u64>,
    pub rolled_back_from_record_id: Option<u64>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub active_page_key: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    SourceId,
    PageId,
    RunId,
    DocumentId,
    VersionKey,
    ContentHash,
    PublishStatus,
    Active,
    ActivatedAt,
    SupersededAt,
    SupersededByRecordId,
    RolledBackFromRecordId,
    CreatedAt,
    UpdatedAt,
    ActivePageKey,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    KnowledgeChunkManifests,
    KnowledgeDocuments,
    KnowledgeIngestionRuns,
    KnowledgeVectorManifests,
    WebIngestionAuditLogs,
    WebPages,
    WebSources,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigUnsigned.def(),
            Self::SourceId => ColumnType::BigUnsigned.def(),
            Self::PageId => ColumnType::BigUnsigned.def(),
            Self::RunId => ColumnType::BigUnsigned.def(),
            Self::DocumentId => ColumnType::BigUnsigned.def(),
            Self::VersionKey => ColumnType::Char(Some(64u32)).def(),
            Self::ContentHash => ColumnType::Char(Some(64u32)).def(),
            Self::PublishStatus => ColumnType::String(StringLen::N(32u32)).def(),
            Self::Active => ColumnType::TinyInteger.def(),
            Self::ActivatedAt => ColumnType::DateTime.def().null(),
            Self::SupersededAt => ColumnType::DateTime.def().null(),
            Self::SupersededByRecordId => ColumnType::BigUnsigned.def().null(),
            Self::RolledBackFromRecordId => ColumnType::BigUnsigned.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::ActivePageKey => ColumnType::String(StringLen::N(128u32))
                .def()
                .null()
                .unique(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::KnowledgeChunkManifests => {
                Entity::has_many(super::knowledge_chunk_manifests::Entity).into()
            }
            Self::KnowledgeDocuments => Entity::belongs_to(super::knowledge_documents::Entity)
                .from(Column::DocumentId)
                .to(super::knowledge_documents::Column::DocumentId)
                .into(),
            Self::KnowledgeIngestionRuns => {
                Entity::belongs_to(super::knowledge_ingestion_runs::Entity)
                    .from(Column::RunId)
                    .to(super::knowledge_ingestion_runs::Column::Id)
                    .into()
            }
            Self::KnowledgeVectorManifests => {
                Entity::has_many(super::knowledge_vector_manifests::Entity).into()
            }
            Self::WebIngestionAuditLogs => {
                Entity::has_many(super::web_ingestion_audit_logs::Entity).into()
            }
            Self::WebPages => Entity::belongs_to(super::web_pages::Entity)
                .from(Column::PageId)
                .to(super::web_pages::Column::Id)
                .into(),
            Self::WebSources => Entity::belongs_to(super::web_sources::Entity)
                .from(Column::SourceId)
                .to(super::web_sources::Column::Id)
                .into(),
        }
    }
}

impl Related<super::knowledge_chunk_manifests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeChunkManifests.def()
    }
}

impl Related<super::knowledge_documents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeDocuments.def()
    }
}

impl Related<super::knowledge_ingestion_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeIngestionRuns.def()
    }
}

impl Related<super::knowledge_vector_manifests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeVectorManifests.def()
    }
}

impl Related<super::web_ingestion_audit_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebIngestionAuditLogs.def()
    }
}

impl Related<super::web_pages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebPages.def()
    }
}

impl Related<super::web_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebSources.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
