//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod community_comments;
pub mod community_post_media;
pub mod community_posts;
pub mod conversation_messages;
pub mod conversations;
pub mod depression_assessments;
pub mod depression_scales;
pub mod music;
pub mod psychology_articles;
pub mod psychology_categories;
pub mod psychology_qna;
pub mod psychology_resources;
pub mod risk_detection_results;
pub mod user_diaries;
pub mod user_knowledge_favorites;
pub mod user_profiles;
pub mod users;
