//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "music")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub music_id: u64,
    pub title: String,
    pub artist: Option<String>,
    pub album: Option<String>,
    pub category: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub duration: Option<u32>,
    #[sea_orm(ignore, column_type = "custom(\"longblob\")", select_as = "text")]
    pub file_data: String,
    pub file_size: u64,
    pub mime_type: String,
    #[sea_orm(column_type = "Binary(255)", nullable)]
    pub cover_image: Option<Vec<u8>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub lyrics: Option<String>,
    pub tags: Option<Json>,
    pub mood_tags: Option<Json>,
    pub status: i8,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
