//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "music"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub music_id: u64,
    pub title: String,
    pub artist: Option<String>,
    pub album: Option<String>,
    pub category: Option<String>,
    pub description: Option<String>,
    pub duration: Option<u32>,
    pub file_data: String,
    pub file_size: u64,
    pub mime_type: String,
    pub cover_image: Option<Vec<u8>>,
    pub lyrics: Option<String>,
    pub tags: Option<Json>,
    pub mood_tags: Option<Json>,
    pub status: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    MusicId,
    Title,
    Artist,
    Album,
    Category,
    Description,
    Duration,
    FileData,
    FileSize,
    MimeType,
    CoverImage,
    Lyrics,
    Tags,
    MoodTags,
    Status,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    MusicId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::MusicId => ColumnType::BigUnsigned.def(),
            Self::Title => ColumnType::String(StringLen::N(200u32)).def(),
            Self::Artist => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::Album => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::Category => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::Description => ColumnType::Text.def().null(),
            Self::Duration => ColumnType::Unsigned.def().null(),
            Self::FileData => ColumnType::custom("longblob").def(),
            Self::FileSize => ColumnType::BigUnsigned.def(),
            Self::MimeType => ColumnType::String(StringLen::N(100u32)).def(),
            Self::CoverImage => ColumnType::Binary(255u32).def().null(),
            Self::Lyrics => ColumnType::Text.def().null(),
            Self::Tags => ColumnType::Json.def().null(),
            Self::MoodTags => ColumnType::Json.def().null(),
            Self::Status => ColumnType::TinyInteger.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
