//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::community_comments::Entity as CommunityComments;
pub use super::community_post_media::Entity as CommunityPostMedia;
pub use super::community_posts::Entity as CommunityPosts;
pub use super::conversation_messages::Entity as ConversationMessages;
pub use super::conversations::Entity as Conversations;
pub use super::depression_assessments::Entity as DepressionAssessments;
pub use super::depression_scales::Entity as DepressionScales;
pub use super::music::Entity as Music;
pub use super::psychology_articles::Entity as PsychologyArticles;
pub use super::psychology_categories::Entity as PsychologyCategories;
pub use super::psychology_qna::Entity as PsychologyQna;
pub use super::psychology_resources::Entity as PsychologyResources;
pub use super::risk_detection_results::Entity as RiskDetectionResults;
pub use super::user_diaries::Entity as UserDiaries;
pub use super::user_knowledge_favorites::Entity as UserKnowledgeFavorites;
pub use super::user_profiles::Entity as UserProfiles;
pub use super::users::Entity as Users;
