//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "psychology_categories"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub category_id: u16,
    pub category_name: String,
    pub parent_id: Option<u16>,
    pub description: Option<String>,
    pub sort_order: i32,
    pub status: i8,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    CategoryId,
    CategoryName,
    ParentId,
    Description,
    SortOrder,
    Status,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    CategoryId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u16;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    PsychologyArticles,
    SelfRef,
    PsychologyQna,
    PsychologyResources,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::CategoryId => ColumnType::SmallUnsigned.def(),
            Self::CategoryName => ColumnType::String(StringLen::N(50u32)).def().unique(),
            Self::ParentId => ColumnType::SmallUnsigned.def().null(),
            Self::Description => ColumnType::Text.def().null(),
            Self::SortOrder => ColumnType::Integer.def(),
            Self::Status => ColumnType::TinyInteger.def(),
            Self::CreatedAt => ColumnType::Timestamp.def(),
            Self::UpdatedAt => ColumnType::Timestamp.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::PsychologyArticles => Entity::has_many(super::psychology_articles::Entity).into(),
            Self::SelfRef => Entity::belongs_to(Entity)
                .from(Column::ParentId)
                .to(Column::CategoryId)
                .into(),
            Self::PsychologyQna => Entity::has_many(super::psychology_qna::Entity).into(),
            Self::PsychologyResources => {
                Entity::has_many(super::psychology_resources::Entity).into()
            }
        }
    }
}

impl Related<super::psychology_articles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PsychologyArticles.def()
    }
}

impl Related<super::psychology_qna::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PsychologyQna.def()
    }
}

impl Related<super::psychology_resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PsychologyResources.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
