//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "psychology_articles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub article_id: u64,
    pub category_id: u16,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub summary: Option<String>,
    #[sea_orm(ignore, column_type = "custom(\"LONGTEXT\")", select_as = "text")]
    pub content: String,
    pub author: Option<String>,
    pub source: Option<String>,
    pub tags: Option<Json>,
    #[sea_orm(column_type = "Binary(255)", nullable)]
    pub cover_image: Option<Vec<u8>>,
    pub view_count: u32,
    pub like_count: u32,
    pub is_featured: i8,
    pub is_published: i8,
    pub publish_date: Option<DateTimeUtc>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::psychology_categories::Entity",
        from = "Column::CategoryId",
        to = "super::psychology_categories::Column::CategoryId",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    PsychologyCategories,
}

impl Related<super::psychology_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PsychologyCategories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
