//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "psychology_qna")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub qna_id: u64,
    pub category_id: u16,
    #[sea_orm(column_type = "Text")]
    pub question: String,
    #[sea_orm(ignore, column_type = "custom(\"LONGTEXT\")", select_as = "text")]
    pub answer: String,
    pub expert_name: Option<String>,
    pub expert_title: Option<String>,
    pub tags: Option<Json>,
    pub view_count: u32,
    pub like_count: u32,
    pub is_verified: i8,
    pub status: i8,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::psychology_categories::Entity",
        from = "Column::CategoryId",
        to = "super::psychology_categories::Column::CategoryId",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    PsychologyCategories,
}

impl Related<super::psychology_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PsychologyCategories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
