//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "psychology_categories")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub category_id: u16,
    #[sea_orm(unique)]
    pub category_name: String,
    pub parent_id: Option<u16>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub sort_order: i32,
    pub status: i8,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::psychology_articles::Entity")]
    PsychologyArticles,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::CategoryId",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::psychology_qna::Entity")]
    PsychologyQna,
    #[sea_orm(has_many = "super::psychology_resources::Entity")]
    PsychologyResources,
}

impl Related<super::psychology_articles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PsychologyArticles.def()
    }
}

impl Related<super::psychology_qna::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PsychologyQna.def()
    }
}

impl Related<super::psychology_resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PsychologyResources.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
