//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "psychology_articles"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub article_id: u64,
    pub category_id: u16,
    pub title: String,
    pub summary: Option<String>,
    pub content: String,
    pub author: Option<String>,
    pub source: Option<String>,
    pub tags: Option<Json>,
    pub cover_image: Option<Vec<u8>>,
    pub view_count: u32,
    pub like_count: u32,
    pub is_featured: i8,
    pub is_published: i8,
    pub publish_date: Option<DateTimeUtc>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    ArticleId,
    CategoryId,
    Title,
    Summary,
    Content,
    Author,
    Source,
    Tags,
    CoverImage,
    ViewCount,
    LikeCount,
    IsFeatured,
    IsPublished,
    PublishDate,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    ArticleId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    PsychologyCategories,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::ArticleId => ColumnType::BigUnsigned.def(),
            Self::CategoryId => ColumnType::SmallUnsigned.def(),
            Self::Title => ColumnType::String(StringLen::N(200u32)).def(),
            Self::Summary => ColumnType::Text.def().null(),
            Self::Content => ColumnType::custom("LONGTEXT").def(),
            Self::Author => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::Source => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::Tags => ColumnType::Json.def().null(),
            Self::CoverImage => ColumnType::Binary(255u32).def().null(),
            Self::ViewCount => ColumnType::Unsigned.def(),
            Self::LikeCount => ColumnType::Unsigned.def(),
            Self::IsFeatured => ColumnType::TinyInteger.def(),
            Self::IsPublished => ColumnType::TinyInteger.def(),
            Self::PublishDate => ColumnType::Timestamp.def().null(),
            Self::CreatedAt => ColumnType::Timestamp.def(),
            Self::UpdatedAt => ColumnType::Timestamp.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::PsychologyCategories => Entity::belongs_to(super::psychology_categories::Entity)
                .from(Column::CategoryId)
                .to(super::psychology_categories::Column::CategoryId)
                .into(),
        }
    }
}

impl Related<super::psychology_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PsychologyCategories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
