//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "psychology_resources")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub resource_id: u64,
    pub category_id: u16,
    pub resource_type: String,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"longblob\")",
        select_as = "text",
        nullable
    )]
    pub file_data: Option<String>,
    pub external_url: Option<String>,
    pub file_size: Option<u64>,
    pub mime_type: Option<String>,
    pub duration: Option<u32>,
    #[sea_orm(column_type = "Binary(255)", nullable)]
    pub thumbnail: Option<Vec<u8>>,
    pub tags: Option<Json>,
    pub view_count: u32,
    pub like_count: u32,
    pub status: i8,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::psychology_categories::Entity",
        from = "Column::CategoryId",
        to = "super::psychology_categories::Column::CategoryId",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    PsychologyCategories,
}

impl Related<super::psychology_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PsychologyCategories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
