//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "stored_objects"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub object_id: u64,
    pub bucket: String,
    pub object_key: String,
    pub original_name: String,
    pub mime_type: String,
    pub size_bytes: u64,
    pub sha256: String,
    pub storage_backend: String,
    pub public_url: Option<String>,
    pub created_by: Option<u64>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    ObjectId,
    Bucket,
    ObjectKey,
    OriginalName,
    MimeType,
    SizeBytes,
    Sha256,
    StorageBackend,
    PublicUrl,
    CreatedBy,
    CreatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    ObjectId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::ObjectId => ColumnType::BigUnsigned.def(),
            Self::Bucket => ColumnType::String(StringLen::N(64u32)).def(),
            Self::ObjectKey => ColumnType::String(StringLen::N(512u32)).def(),
            Self::OriginalName => ColumnType::String(StringLen::N(255u32)).def(),
            Self::MimeType => ColumnType::String(StringLen::N(128u32)).def(),
            Self::SizeBytes => ColumnType::BigUnsigned.def(),
            Self::Sha256 => ColumnType::Char(Some(64u32)).def(),
            Self::StorageBackend => ColumnType::String(StringLen::N(32u32)).def(),
            Self::PublicUrl => ColumnType::Text.def().null(),
            Self::CreatedBy => ColumnType::BigUnsigned.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::CreatedBy)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
