//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_memory_embeddings")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub embedding_id: u64,
    #[sea_orm(unique_key = "uk_user_memory_embeddings_memory_model")]
    pub memory_id: u64,
    #[sea_orm(unique_key = "uk_user_memory_embeddings_memory_model")]
    pub provider: String,
    #[sea_orm(unique_key = "uk_user_memory_embeddings_memory_model")]
    pub model: String,
    pub dimension: u32,
    pub embedding_json: Json,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_memories::Entity",
        from = "Column::MemoryId",
        to = "super::user_memories::Column::MemoryId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    UserMemories,
}

impl Related<super::user_memories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMemories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
