//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "user_profiles"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: u64,
    pub user_id: u64,
    pub interests: Option<Json>,
    pub personality_traits: Option<Json>,
    pub interaction_preferences: Option<Json>,
    pub emotional_tendency: Option<Json>,
    pub learning_records: Option<Json>,
    pub personalization_enabled: i8,
    pub personalization_reset_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    UserId,
    Interests,
    PersonalityTraits,
    InteractionPreferences,
    EmotionalTendency,
    LearningRecords,
    PersonalizationEnabled,
    PersonalizationResetAt,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigUnsigned.def(),
            Self::UserId => ColumnType::BigUnsigned.def().unique(),
            Self::Interests => ColumnType::Json.def().null(),
            Self::PersonalityTraits => ColumnType::Json.def().null(),
            Self::InteractionPreferences => ColumnType::Json.def().null(),
            Self::EmotionalTendency => ColumnType::Json.def().null(),
            Self::LearningRecords => ColumnType::Json.def().null(),
            Self::PersonalizationEnabled => ColumnType::TinyInteger.def(),
            Self::PersonalizationResetAt => ColumnType::DateTime.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::UserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
