//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "user_memory_evidence"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub evidence_id: u64,
    pub memory_id: u64,
    pub source_type: String,
    pub source_ref_id: u64,
    pub message_id: Option<u64>,
    pub summary_id: Option<u64>,
    pub source_deleted: i8,
    pub evidence_type: String,
    pub confidence: Option<Decimal>,
    pub extractor_version: Option<String>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    EvidenceId,
    MemoryId,
    SourceType,
    SourceRefId,
    MessageId,
    SummaryId,
    SourceDeleted,
    EvidenceType,
    Confidence,
    ExtractorVersion,
    CreatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    EvidenceId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ConversationMessages,
    ConversationSummaries,
    UserMemories,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::EvidenceId => ColumnType::BigUnsigned.def(),
            Self::MemoryId => ColumnType::BigUnsigned.def(),
            Self::SourceType => ColumnType::String(StringLen::N(32u32)).def(),
            Self::SourceRefId => ColumnType::BigUnsigned.def(),
            Self::MessageId => ColumnType::BigUnsigned.def().null(),
            Self::SummaryId => ColumnType::BigUnsigned.def().null(),
            Self::SourceDeleted => ColumnType::TinyInteger.def(),
            Self::EvidenceType => ColumnType::String(StringLen::N(32u32)).def(),
            Self::Confidence => ColumnType::Decimal(Some((4u32, 3u32))).def().null(),
            Self::ExtractorVersion => ColumnType::String(StringLen::N(64u32)).def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ConversationMessages => Entity::belongs_to(super::conversation_messages::Entity)
                .from(Column::MessageId)
                .to(super::conversation_messages::Column::Id)
                .into(),
            Self::ConversationSummaries => {
                Entity::belongs_to(super::conversation_summaries::Entity)
                    .from(Column::SummaryId)
                    .to(super::conversation_summaries::Column::SummaryId)
                    .into()
            }
            Self::UserMemories => Entity::belongs_to(super::user_memories::Entity)
                .from(Column::MemoryId)
                .to(super::user_memories::Column::MemoryId)
                .into(),
        }
    }
}

impl Related<super::conversation_messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConversationMessages.def()
    }
}

impl Related<super::conversation_summaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConversationSummaries.def()
    }
}

impl Related<super::user_memories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMemories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
