//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique)]
    pub username: String,
    pub password: String,
    #[sea_orm(unique)]
    pub email: Option<String>,
    #[sea_orm(unique)]
    pub phone: Option<String>,
    #[sea_orm(column_type = "Binary(255)", nullable)]
    pub avatar: Option<Vec<u8>>,
    pub nickname: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub last_login_at: Option<DateTimeUtc>,
    pub status: i8,
    pub role: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::agent_events::Entity")]
    AgentEvents,
    #[sea_orm(has_many = "super::community_comments::Entity")]
    CommunityComments,
    #[sea_orm(has_many = "super::community_posts::Entity")]
    CommunityPosts,
    #[sea_orm(has_many = "super::content_likes::Entity")]
    ContentLikes,
    #[sea_orm(has_many = "super::conversation_summaries::Entity")]
    ConversationSummaries,
    #[sea_orm(has_many = "super::conversations::Entity")]
    Conversations,
    #[sea_orm(has_many = "super::depression_assessments::Entity")]
    DepressionAssessments,
    #[sea_orm(has_many = "super::knowledge_documents::Entity")]
    KnowledgeDocuments,
    #[sea_orm(has_many = "super::refresh_tokens::Entity")]
    RefreshTokens,
    #[sea_orm(has_many = "super::risk_detection_results::Entity")]
    RiskDetectionResults,
    #[sea_orm(has_many = "super::user_diaries::Entity")]
    UserDiaries,
    #[sea_orm(has_many = "super::user_knowledge_favorites::Entity")]
    UserKnowledgeFavorites,
    #[sea_orm(has_many = "super::user_memories::Entity")]
    UserMemories,
    #[sea_orm(has_one = "super::user_profiles::Entity")]
    UserProfiles,
    #[sea_orm(has_many = "super::vector_index_records::Entity")]
    VectorIndexRecords,
}

impl Related<super::agent_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentEvents.def()
    }
}

impl Related<super::community_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommunityComments.def()
    }
}

impl Related<super::community_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommunityPosts.def()
    }
}

impl Related<super::content_likes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentLikes.def()
    }
}

impl Related<super::conversation_summaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConversationSummaries.def()
    }
}

impl Related<super::conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Conversations.def()
    }
}

impl Related<super::depression_assessments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DepressionAssessments.def()
    }
}

impl Related<super::knowledge_documents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeDocuments.def()
    }
}

impl Related<super::refresh_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefreshTokens.def()
    }
}

impl Related<super::risk_detection_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RiskDetectionResults.def()
    }
}

impl Related<super::user_diaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserDiaries.def()
    }
}

impl Related<super::user_knowledge_favorites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserKnowledgeFavorites.def()
    }
}

impl Related<super::user_memories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMemories.def()
    }
}

impl Related<super::user_profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserProfiles.def()
    }
}

impl Related<super::vector_index_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VectorIndexRecords.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
