//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_memories")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub memory_id: u64,
    pub user_id: u64,
    pub memory_type: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[sea_orm(column_type = "Double")]
    pub confidence: f64,
    pub source_conversation_id: Option<u64>,
    pub source_message_id: Option<u64>,
    pub status: i8,
    pub metadata: Option<Json>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::conversation_messages::Entity",
        from = "Column::SourceMessageId",
        to = "super::conversation_messages::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    ConversationMessages,
    #[sea_orm(
        belongs_to = "super::conversations::Entity",
        from = "Column::SourceConversationId",
        to = "super::conversations::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Conversations,
    #[sea_orm(has_many = "super::user_memory_embeddings::Entity")]
    UserMemoryEmbeddings,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::conversation_messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConversationMessages.def()
    }
}

impl Related<super::conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Conversations.def()
    }
}

impl Related<super::user_memory_embeddings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMemoryEmbeddings.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
