//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "vector_index_records")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub record_id: u64,
    #[sea_orm(unique)]
    pub vector_id: String,
    pub collection_name: String,
    pub object_type: String,
    pub object_id: u64,
    pub owner_user_id: Option<u64>,
    pub source_table: String,
    pub source_hash: Option<String>,
    pub embedding_provider: String,
    pub embedding_model: String,
    pub embedding_dimension: u32,
    pub payload: Json,
    pub index_status: String,
    pub indexed_at: Option<DateTime>,
    pub failed_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::OwnerUserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
