//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "vector_index_jobs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub job_id: u64,
    pub action: String,
    pub object_type: String,
    pub object_id: u64,
    pub collection_name: String,
    pub vector_id: Option<String>,
    pub priority: i32,
    pub status: String,
    pub attempts: u32,
    pub max_attempts: u32,
    pub next_run_at: DateTime,
    pub locked_at: Option<DateTime>,
    pub locked_by: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
