//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "vector_index_jobs"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub job_id: u64,
    pub action: String,
    pub object_type: String,
    pub object_id: u64,
    pub collection_name: String,
    pub vector_id: Option<String>,
    pub priority: i32,
    pub status: String,
    pub attempts: u32,
    pub max_attempts: u32,
    pub next_run_at: DateTime,
    pub locked_at: Option<DateTime>,
    pub locked_by: Option<String>,
    pub last_error: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    JobId,
    Action,
    ObjectType,
    ObjectId,
    CollectionName,
    VectorId,
    Priority,
    Status,
    Attempts,
    MaxAttempts,
    NextRunAt,
    LockedAt,
    LockedBy,
    LastError,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    JobId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::JobId => ColumnType::BigUnsigned.def(),
            Self::Action => ColumnType::String(StringLen::N(32u32)).def(),
            Self::ObjectType => ColumnType::String(StringLen::N(64u32)).def(),
            Self::ObjectId => ColumnType::BigUnsigned.def(),
            Self::CollectionName => ColumnType::String(StringLen::N(128u32)).def(),
            Self::VectorId => ColumnType::String(StringLen::N(128u32)).def().null(),
            Self::Priority => ColumnType::Integer.def(),
            Self::Status => ColumnType::String(StringLen::N(32u32)).def(),
            Self::Attempts => ColumnType::Unsigned.def(),
            Self::MaxAttempts => ColumnType::Unsigned.def(),
            Self::NextRunAt => ColumnType::DateTime.def(),
            Self::LockedAt => ColumnType::DateTime.def().null(),
            Self::LockedBy => ColumnType::String(StringLen::N(128u32)).def().null(),
            Self::LastError => ColumnType::Text.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
