//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "vector_index_records"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub record_id: u64,
    pub vector_id: String,
    pub collection_name: String,
    pub object_type: String,
    pub object_id: u64,
    pub owner_user_id: Option<u64>,
    pub source_table: String,
    pub source_hash: Option<String>,
    pub embedding_provider: String,
    pub embedding_model: String,
    pub embedding_dimension: u32,
    pub payload: Json,
    pub index_status: String,
    pub indexed_at: Option<DateTime>,
    pub failed_at: Option<DateTime>,
    pub error_message: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    RecordId,
    VectorId,
    CollectionName,
    ObjectType,
    ObjectId,
    OwnerUserId,
    SourceTable,
    SourceHash,
    EmbeddingProvider,
    EmbeddingModel,
    EmbeddingDimension,
    Payload,
    IndexStatus,
    IndexedAt,
    FailedAt,
    ErrorMessage,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    RecordId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::RecordId => ColumnType::BigUnsigned.def(),
            Self::VectorId => ColumnType::String(StringLen::N(128u32)).def().unique(),
            Self::CollectionName => ColumnType::String(StringLen::N(128u32)).def(),
            Self::ObjectType => ColumnType::String(StringLen::N(64u32)).def(),
            Self::ObjectId => ColumnType::BigUnsigned.def(),
            Self::OwnerUserId => ColumnType::BigUnsigned.def().null(),
            Self::SourceTable => ColumnType::String(StringLen::N(64u32)).def(),
            Self::SourceHash => ColumnType::Char(Some(64u32)).def().null(),
            Self::EmbeddingProvider => ColumnType::String(StringLen::N(64u32)).def(),
            Self::EmbeddingModel => ColumnType::String(StringLen::N(128u32)).def(),
            Self::EmbeddingDimension => ColumnType::Unsigned.def(),
            Self::Payload => ColumnType::Json.def(),
            Self::IndexStatus => ColumnType::String(StringLen::N(32u32)).def(),
            Self::IndexedAt => ColumnType::DateTime.def().null(),
            Self::FailedAt => ColumnType::DateTime.def().null(),
            Self::ErrorMessage => ColumnType::Text.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::OwnerUserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
