//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "web_ingestion_audit_logs"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: u64,
    pub source_id: Option<u64>,
    pub source_url_id: Option<u64>,
    pub page_id: Option<u64>,
    pub run_id: Option<u64>,
    pub publish_record_id: Option<u64>,
    pub action: String,
    pub status: String,
    pub message: String,
    pub metadata: Option<Json>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    SourceId,
    SourceUrlId,
    PageId,
    RunId,
    PublishRecordId,
    Action,
    Status,
    Message,
    Metadata,
    CreatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    KnowledgeIngestionRuns,
    KnowledgePublishRecords,
    WebPages,
    WebSourceUrls,
    WebSources,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigUnsigned.def(),
            Self::SourceId => ColumnType::BigUnsigned.def().null(),
            Self::SourceUrlId => ColumnType::BigUnsigned.def().null(),
            Self::PageId => ColumnType::BigUnsigned.def().null(),
            Self::RunId => ColumnType::BigUnsigned.def().null(),
            Self::PublishRecordId => ColumnType::BigUnsigned.def().null(),
            Self::Action => ColumnType::String(StringLen::N(64u32)).def(),
            Self::Status => ColumnType::String(StringLen::N(32u32)).def(),
            Self::Message => ColumnType::Text.def(),
            Self::Metadata => ColumnType::Json.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::KnowledgeIngestionRuns => {
                Entity::belongs_to(super::knowledge_ingestion_runs::Entity)
                    .from(Column::RunId)
                    .to(super::knowledge_ingestion_runs::Column::Id)
                    .into()
            }
            Self::KnowledgePublishRecords => {
                Entity::belongs_to(super::knowledge_publish_records::Entity)
                    .from(Column::PublishRecordId)
                    .to(super::knowledge_publish_records::Column::Id)
                    .into()
            }
            Self::WebPages => Entity::belongs_to(super::web_pages::Entity)
                .from(Column::PageId)
                .to(super::web_pages::Column::Id)
                .into(),
            Self::WebSourceUrls => Entity::belongs_to(super::web_source_urls::Entity)
                .from(Column::SourceUrlId)
                .to(super::web_source_urls::Column::Id)
                .into(),
            Self::WebSources => Entity::belongs_to(super::web_sources::Entity)
                .from(Column::SourceId)
                .to(super::web_sources::Column::Id)
                .into(),
        }
    }
}

impl Related<super::knowledge_ingestion_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeIngestionRuns.def()
    }
}

impl Related<super::knowledge_publish_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgePublishRecords.def()
    }
}

impl Related<super::web_pages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebPages.def()
    }
}

impl Related<super::web_source_urls::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebSourceUrls.def()
    }
}

impl Related<super::web_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebSources.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
