//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "web_pages"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: u64,
    pub source_id: u64,
    pub source_url_id: Option<u64>,
    pub url: String,
    pub canonical_url: Option<String>,
    pub url_hash: String,
    pub latest_content_hash: Option<String>,
    pub latest_success_run_id: Option<u64>,
    pub last_fetched_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    SourceId,
    SourceUrlId,
    Url,
    CanonicalUrl,
    UrlHash,
    LatestContentHash,
    LatestSuccessRunId,
    LastFetchedAt,
    CreatedAt,
    UpdatedAt,
    DeletedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    KnowledgeIngestionRuns,
    KnowledgePublishRecords,
    WebIngestionAuditLogs,
    WebSourceUrls,
    WebSources,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigUnsigned.def(),
            Self::SourceId => ColumnType::BigUnsigned.def(),
            Self::SourceUrlId => ColumnType::BigUnsigned.def().null(),
            Self::Url => ColumnType::Text.def(),
            Self::CanonicalUrl => ColumnType::Text.def().null(),
            Self::UrlHash => ColumnType::Char(Some(64u32)).def(),
            Self::LatestContentHash => ColumnType::Char(Some(64u32)).def().null(),
            Self::LatestSuccessRunId => ColumnType::BigUnsigned.def().null(),
            Self::LastFetchedAt => ColumnType::DateTime.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::DeletedAt => ColumnType::DateTime.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::KnowledgeIngestionRuns => {
                Entity::has_many(super::knowledge_ingestion_runs::Entity).into()
            }
            Self::KnowledgePublishRecords => {
                Entity::has_many(super::knowledge_publish_records::Entity).into()
            }
            Self::WebIngestionAuditLogs => {
                Entity::has_many(super::web_ingestion_audit_logs::Entity).into()
            }
            Self::WebSourceUrls => Entity::belongs_to(super::web_source_urls::Entity)
                .from(Column::SourceUrlId)
                .to(super::web_source_urls::Column::Id)
                .into(),
            Self::WebSources => Entity::belongs_to(super::web_sources::Entity)
                .from(Column::SourceId)
                .to(super::web_sources::Column::Id)
                .into(),
        }
    }
}

impl Related<super::knowledge_ingestion_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeIngestionRuns.def()
    }
}

impl Related<super::knowledge_publish_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgePublishRecords.def()
    }
}

impl Related<super::web_ingestion_audit_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebIngestionAuditLogs.def()
    }
}

impl Related<super::web_source_urls::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebSourceUrls.def()
    }
}

impl Related<super::web_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebSources.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
