//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "web_crawl_jobs"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: u64,
    pub source_id: Option<u64>,
    pub status: String,
    pub scheduled_at: DateTime,
    pub started_at: Option<DateTime>,
    pub finished_at: Option<DateTime>,
    pub last_error: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    SourceId,
    Status,
    ScheduledAt,
    StartedAt,
    FinishedAt,
    LastError,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    KnowledgeIngestionRuns,
    WebSources,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigUnsigned.def(),
            Self::SourceId => ColumnType::BigUnsigned.def().null(),
            Self::Status => ColumnType::String(StringLen::N(32u32)).def(),
            Self::ScheduledAt => ColumnType::DateTime.def(),
            Self::StartedAt => ColumnType::DateTime.def().null(),
            Self::FinishedAt => ColumnType::DateTime.def().null(),
            Self::LastError => ColumnType::Text.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::KnowledgeIngestionRuns => {
                Entity::has_many(super::knowledge_ingestion_runs::Entity).into()
            }
            Self::WebSources => Entity::belongs_to(super::web_sources::Entity)
                .from(Column::SourceId)
                .to(super::web_sources::Column::Id)
                .into(),
        }
    }
}

impl Related<super::knowledge_ingestion_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeIngestionRuns.def()
    }
}

impl Related<super::web_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebSources.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
