[package]
name = "qqbot"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
futures-util.workspace = true
regex.workspace = true
reqwest = { workspace = true, features = ["json", "native-tls"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tokio-tungstenite = { workspace = true, features = ["native-tls"] }
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
