//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "fresh_topics"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub id: u64,
    pub topic_key: String,
    pub title: String,
    pub summary: Option<String>,
    pub entities: Option<Json>,
    pub first_seen_at: DateTime,
    pub last_seen_at: DateTime,
    pub heat_score: f64,
    pub freshness_score: f64,
    pub expires_at: DateTime,
    pub status: String,
    pub risk_flags: Option<Json>,
    pub metadata: Option<Json>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    TopicKey,
    Title,
    Summary,
    Entities,
    FirstSeenAt,
    LastSeenAt,
    HeatScore,
    FreshnessScore,
    ExpiresAt,
    Status,
    RiskFlags,
    Metadata,
    CreatedAt,
    UpdatedAt,
    DeletedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    FreshChunks,
    FreshTopicEvidence,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigUnsigned.def(),
            Self::TopicKey => ColumnType::Char(Some(64u32)).def().unique(),
            Self::Title => ColumnType::String(StringLen::N(512u32)).def(),
            Self::Summary => ColumnType::custom("MEDIUMTEXT").def().null(),
            Self::Entities => ColumnType::Json.def().null(),
            Self::FirstSeenAt => ColumnType::DateTime.def(),
            Self::LastSeenAt => ColumnType::DateTime.def(),
            Self::HeatScore => ColumnType::Double.def(),
            Self::FreshnessScore => ColumnType::Double.def(),
            Self::ExpiresAt => ColumnType::DateTime.def(),
            Self::Status => ColumnType::String(StringLen::N(32u32)).def(),
            Self::RiskFlags => ColumnType::Json.def().null(),
            Self::Metadata => ColumnType::Json.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::DeletedAt => ColumnType::DateTime.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::FreshChunks => Entity::has_many(super::fresh_chunks::Entity).into(),
            Self::FreshTopicEvidence => {
                Entity::has_many(super::fresh_topic_evidence::Entity).into()
            }
        }
    }
}

impl Related<super::fresh_chunks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FreshChunks.def()
    }
}

impl Related<super::fresh_topic_evidence::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FreshTopicEvidence.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
