//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "fresh_items"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub id: u64,
    pub source_id: u64,
    pub url: Option<String>,
    pub canonical_url: Option<String>,
    pub url_hash: Option<String>,
    pub title: Option<String>,
    pub raw_text: Option<String>,
    pub clean_text: Option<String>,
    pub summary: Option<String>,
    pub published_at: Option<DateTime>,
    pub fetched_at: DateTime,
    pub expires_at: DateTime,
    pub content_hash: String,
    pub status: String,
    pub reliability_score: f64,
    pub freshness_score: f64,
    pub heat_score: f64,
    pub rumor_level: String,
    pub risk_flags: Option<Json>,
    pub metadata: Option<Json>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    SourceId,
    Url,
    CanonicalUrl,
    UrlHash,
    Title,
    RawText,
    CleanText,
    Summary,
    PublishedAt,
    FetchedAt,
    ExpiresAt,
    ContentHash,
    Status,
    ReliabilityScore,
    FreshnessScore,
    HeatScore,
    RumorLevel,
    RiskFlags,
    Metadata,
    CreatedAt,
    UpdatedAt,
    DeletedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    FreshChunks,
    FreshSources,
    FreshTopicEvidence,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigUnsigned.def(),
            Self::SourceId => ColumnType::BigUnsigned.def(),
            Self::Url => ColumnType::Text.def().null(),
            Self::CanonicalUrl => ColumnType::Text.def().null(),
            Self::UrlHash => ColumnType::Char(Some(64u32)).def().null(),
            Self::Title => ColumnType::String(StringLen::N(512u32)).def().null(),
            Self::RawText => ColumnType::custom("MEDIUMTEXT").def().null(),
            Self::CleanText => ColumnType::custom("MEDIUMTEXT").def().null(),
            Self::Summary => ColumnType::custom("MEDIUMTEXT").def().null(),
            Self::PublishedAt => ColumnType::DateTime.def().null(),
            Self::FetchedAt => ColumnType::DateTime.def(),
            Self::ExpiresAt => ColumnType::DateTime.def(),
            Self::ContentHash => ColumnType::Char(Some(64u32)).def(),
            Self::Status => ColumnType::String(StringLen::N(32u32)).def(),
            Self::ReliabilityScore => ColumnType::Double.def(),
            Self::FreshnessScore => ColumnType::Double.def(),
            Self::HeatScore => ColumnType::Double.def(),
            Self::RumorLevel => ColumnType::String(StringLen::N(32u32)).def(),
            Self::RiskFlags => ColumnType::Json.def().null(),
            Self::Metadata => ColumnType::Json.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::DeletedAt => ColumnType::DateTime.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::FreshChunks => Entity::has_many(super::fresh_chunks::Entity).into(),
            Self::FreshSources => Entity::belongs_to(super::fresh_sources::Entity)
                .from(Column::SourceId)
                .to(super::fresh_sources::Column::Id)
                .into(),
            Self::FreshTopicEvidence => {
                Entity::has_many(super::fresh_topic_evidence::Entity).into()
            }
        }
    }
}

impl Related<super::fresh_chunks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FreshChunks.def()
    }
}

impl Related<super::fresh_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FreshSources.def()
    }
}

impl Related<super::fresh_topic_evidence::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FreshTopicEvidence.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
