//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "fresh_chunks"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: u64,
    pub item_id: u64,
    pub topic_id: Option<u64>,
    pub chunk_index: u32,
    pub content: String,
    pub content_hash: String,
    pub token_count: Option<u32>,
    pub metadata: Option<Json>,
    pub vector_id: Option<String>,
    pub embedding_provider: Option<String>,
    pub embedding_model: Option<String>,
    pub embedding_dimension: Option<u32>,
    pub active: i8,
    pub indexed_at: Option<DateTime>,
    pub expires_at: DateTime,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    ItemId,
    TopicId,
    ChunkIndex,
    Content,
    ContentHash,
    TokenCount,
    Metadata,
    VectorId,
    EmbeddingProvider,
    EmbeddingModel,
    EmbeddingDimension,
    Active,
    IndexedAt,
    ExpiresAt,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    FreshItems,
    FreshTopics,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigUnsigned.def(),
            Self::ItemId => ColumnType::BigUnsigned.def(),
            Self::TopicId => ColumnType::BigUnsigned.def().null(),
            Self::ChunkIndex => ColumnType::Unsigned.def(),
            Self::Content => ColumnType::Text.def(),
            Self::ContentHash => ColumnType::Char(Some(64u32)).def(),
            Self::TokenCount => ColumnType::Unsigned.def().null(),
            Self::Metadata => ColumnType::Json.def().null(),
            Self::VectorId => ColumnType::String(StringLen::N(128u32))
                .def()
                .null()
                .unique(),
            Self::EmbeddingProvider => ColumnType::String(StringLen::N(64u32)).def().null(),
            Self::EmbeddingModel => ColumnType::String(StringLen::N(128u32)).def().null(),
            Self::EmbeddingDimension => ColumnType::Unsigned.def().null(),
            Self::Active => ColumnType::TinyInteger.def(),
            Self::IndexedAt => ColumnType::DateTime.def().null(),
            Self::ExpiresAt => ColumnType::DateTime.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::FreshItems => Entity::belongs_to(super::fresh_items::Entity)
                .from(Column::ItemId)
                .to(super::fresh_items::Column::Id)
                .into(),
            Self::FreshTopics => Entity::belongs_to(super::fresh_topics::Entity)
                .from(Column::TopicId)
                .to(super::fresh_topics::Column::Id)
                .into(),
        }
    }
}

impl Related<super::fresh_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FreshItems.def()
    }
}

impl Related<super::fresh_topics::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FreshTopics.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
