//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "post_conversation_risk_audits"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub audit_id: u64,
    pub user_id: u64,
    pub conversation_id: u64,
    pub audit_scope: String,
    pub user_message_ref_id: Option<u64>,
    pub assistant_message_ref_id: Option<u64>,
    pub user_message_id: Option<u64>,
    pub assistant_message_id: Option<u64>,
    pub status: String,
    pub risk_level: Option<String>,
    pub risk_categories: Option<Json>,
    pub confidence: Option<Decimal>,
    pub input_hash: Option<String>,
    pub detector_name: Option<String>,
    pub detector_version: Option<String>,
    pub model_name: Option<String>,
    pub checked_at: Option<DateTime>,
    pub error_message: Option<String>,
    pub metadata: Option<Json>,
    pub source_deleted: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    AuditId,
    UserId,
    ConversationId,
    AuditScope,
    UserMessageRefId,
    AssistantMessageRefId,
    UserMessageId,
    AssistantMessageId,
    Status,
    RiskLevel,
    RiskCategories,
    Confidence,
    InputHash,
    DetectorName,
    DetectorVersion,
    ModelName,
    CheckedAt,
    ErrorMessage,
    Metadata,
    SourceDeleted,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    AuditId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ConversationMessages2,
    ConversationMessages1,
    Conversations,
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::AuditId => ColumnType::BigUnsigned.def(),
            Self::UserId => ColumnType::BigUnsigned.def(),
            Self::ConversationId => ColumnType::BigUnsigned.def(),
            Self::AuditScope => ColumnType::String(StringLen::N(32u32)).def(),
            Self::UserMessageRefId => ColumnType::BigUnsigned.def().null(),
            Self::AssistantMessageRefId => ColumnType::BigUnsigned.def().null(),
            Self::UserMessageId => ColumnType::BigUnsigned.def().null(),
            Self::AssistantMessageId => ColumnType::BigUnsigned.def().null(),
            Self::Status => ColumnType::String(StringLen::N(32u32)).def(),
            Self::RiskLevel => ColumnType::String(StringLen::N(32u32)).def().null(),
            Self::RiskCategories => ColumnType::Json.def().null(),
            Self::Confidence => ColumnType::Decimal(Some((4u32, 3u32))).def().null(),
            Self::InputHash => ColumnType::Char(Some(64u32)).def().null(),
            Self::DetectorName => ColumnType::String(StringLen::N(128u32)).def().null(),
            Self::DetectorVersion => ColumnType::String(StringLen::N(64u32)).def().null(),
            Self::ModelName => ColumnType::String(StringLen::N(128u32)).def().null(),
            Self::CheckedAt => ColumnType::DateTime.def().null(),
            Self::ErrorMessage => ColumnType::Text.def().null(),
            Self::Metadata => ColumnType::Json.def().null(),
            Self::SourceDeleted => ColumnType::TinyInteger.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ConversationMessages2 => Entity::belongs_to(super::conversation_messages::Entity)
                .from(Column::UserMessageId)
                .to(super::conversation_messages::Column::Id)
                .into(),
            Self::ConversationMessages1 => Entity::belongs_to(super::conversation_messages::Entity)
                .from(Column::AssistantMessageId)
                .to(super::conversation_messages::Column::Id)
                .into(),
            Self::Conversations => Entity::belongs_to(super::conversations::Entity)
                .from(Column::ConversationId)
                .to(super::conversations::Column::Id)
                .into(),
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::UserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Conversations.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
