//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "qq_groups"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub qq_group_id: i64,
    pub group_name: Option<String>,
    pub bot_account_id: u64,
    pub enabled: i8,
    pub trigger_policy: String,
    pub cooldown_secs: u64,
    pub max_segments: u32,
    pub max_chars_per_segment: u32,
    pub allow_proactive: i8,
    pub keywords: Option<Json>,
    pub memory_policy: String,
    pub last_seen_at: Option<i64>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    QqGroupId,
    GroupName,
    BotAccountId,
    Enabled,
    TriggerPolicy,
    CooldownSecs,
    MaxSegments,
    MaxCharsPerSegment,
    AllowProactive,
    Keywords,
    MemoryPolicy,
    LastSeenAt,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    QqGroupId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    QqBotAccounts,
    QqGroupMembers,
    QqGroupMemories,
    QqGroupMessages,
    QqGroupSummaries,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::QqGroupId => ColumnType::BigInteger.def(),
            Self::GroupName => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::BotAccountId => ColumnType::BigUnsigned.def(),
            Self::Enabled => ColumnType::TinyInteger.def(),
            Self::TriggerPolicy => ColumnType::String(StringLen::N(20u32)).def(),
            Self::CooldownSecs => ColumnType::BigUnsigned.def(),
            Self::MaxSegments => ColumnType::Unsigned.def(),
            Self::MaxCharsPerSegment => ColumnType::Unsigned.def(),
            Self::AllowProactive => ColumnType::TinyInteger.def(),
            Self::Keywords => ColumnType::Json.def().null(),
            Self::MemoryPolicy => ColumnType::String(StringLen::N(15u32)).def(),
            Self::LastSeenAt => ColumnType::BigInteger.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::QqBotAccounts => Entity::belongs_to(super::qq_bot_accounts::Entity)
                .from(Column::BotAccountId)
                .to(super::qq_bot_accounts::Column::BotAccountId)
                .into(),
            Self::QqGroupMembers => Entity::has_many(super::qq_group_members::Entity).into(),
            Self::QqGroupMemories => Entity::has_many(super::qq_group_memories::Entity).into(),
            Self::QqGroupMessages => Entity::has_many(super::qq_group_messages::Entity).into(),
            Self::QqGroupSummaries => Entity::has_many(super::qq_group_summaries::Entity).into(),
        }
    }
}

impl Related<super::qq_bot_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqBotAccounts.def()
    }
}

impl Related<super::qq_group_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqGroupMembers.def()
    }
}

impl Related<super::qq_group_memories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqGroupMemories.def()
    }
}

impl Related<super::qq_group_messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqGroupMessages.def()
    }
}

impl Related<super::qq_group_summaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqGroupSummaries.def()
    }
}

impl Related<super::qq_external_users::Entity> for Entity {
    fn to() -> RelationDef {
        super::qq_group_members::Relation::QqExternalUsers.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::qq_group_members::Relation::QqGroups.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
