//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "qq_group_messages"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: u64,
    pub bot_account_id: u64,
    pub qq_group_id: i64,
    pub qq_user_id: Option<i64>,
    pub platform_message_id: String,
    pub direction: String,
    pub raw_text: String,
    pub normalized_text: String,
    pub segments: Json,
    pub at_bot: i8,
    pub command_name: Option<String>,
    pub sent_at: i64,
    pub status: String,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    BotAccountId,
    QqGroupId,
    QqUserId,
    PlatformMessageId,
    Direction,
    RawText,
    NormalizedText,
    Segments,
    AtBot,
    CommandName,
    SentAt,
    Status,
    CreatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    QqBotAccounts,
    QqExternalUsers,
    QqGroupMemories,
    QqGroups,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigUnsigned.def(),
            Self::BotAccountId => ColumnType::BigUnsigned.def(),
            Self::QqGroupId => ColumnType::BigInteger.def(),
            Self::QqUserId => ColumnType::BigInteger.def().null(),
            Self::PlatformMessageId => ColumnType::String(StringLen::N(64u32)).def(),
            Self::Direction => ColumnType::String(StringLen::N(10u32)).def(),
            Self::RawText => ColumnType::Text.def(),
            Self::NormalizedText => ColumnType::Text.def(),
            Self::Segments => ColumnType::Json.def(),
            Self::AtBot => ColumnType::TinyInteger.def(),
            Self::CommandName => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::SentAt => ColumnType::BigInteger.def(),
            Self::Status => ColumnType::String(StringLen::N(15u32)).def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::QqBotAccounts => Entity::belongs_to(super::qq_bot_accounts::Entity)
                .from(Column::BotAccountId)
                .to(super::qq_bot_accounts::Column::BotAccountId)
                .into(),
            Self::QqExternalUsers => Entity::belongs_to(super::qq_external_users::Entity)
                .from(Column::QqUserId)
                .to(super::qq_external_users::Column::QqUserId)
                .into(),
            Self::QqGroupMemories => Entity::has_many(super::qq_group_memories::Entity).into(),
            Self::QqGroups => Entity::belongs_to(super::qq_groups::Entity)
                .from(Column::QqGroupId)
                .to(super::qq_groups::Column::QqGroupId)
                .into(),
        }
    }
}

impl Related<super::qq_bot_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqBotAccounts.def()
    }
}

impl Related<super::qq_external_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqExternalUsers.def()
    }
}

impl Related<super::qq_group_memories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqGroupMemories.def()
    }
}

impl Related<super::qq_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqGroups.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
