//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "qq_message_outbox"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub outbox_id: u64,
    pub bot_account_id: u64,
    pub qq_group_id: Option<i64>,
    pub qq_user_id: Option<i64>,
    pub target_type: String,
    pub payload: Json,
    pub related_turn_id: Option<u64>,
    pub status: String,
    pub attempts: u32,
    pub max_attempts: u32,
    pub next_run_at: i64,
    pub platform_message_id: Option<String>,
    pub last_error: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    OutboxId,
    BotAccountId,
    QqGroupId,
    QqUserId,
    TargetType,
    Payload,
    RelatedTurnId,
    Status,
    Attempts,
    MaxAttempts,
    NextRunAt,
    PlatformMessageId,
    LastError,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    OutboxId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    QqAgentTurns,
    QqBotAccounts,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::OutboxId => ColumnType::BigUnsigned.def(),
            Self::BotAccountId => ColumnType::BigUnsigned.def(),
            Self::QqGroupId => ColumnType::BigInteger.def().null(),
            Self::QqUserId => ColumnType::BigInteger.def().null(),
            Self::TargetType => ColumnType::String(StringLen::N(10u32)).def(),
            Self::Payload => ColumnType::Json.def(),
            Self::RelatedTurnId => ColumnType::BigUnsigned.def().null(),
            Self::Status => ColumnType::String(StringLen::N(15u32)).def(),
            Self::Attempts => ColumnType::Unsigned.def(),
            Self::MaxAttempts => ColumnType::Unsigned.def(),
            Self::NextRunAt => ColumnType::BigInteger.def(),
            Self::PlatformMessageId => ColumnType::String(StringLen::N(64u32)).def().null(),
            Self::LastError => ColumnType::Text.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::QqAgentTurns => Entity::belongs_to(super::qq_agent_turns::Entity)
                .from(Column::RelatedTurnId)
                .to(super::qq_agent_turns::Column::TurnId)
                .into(),
            Self::QqBotAccounts => Entity::belongs_to(super::qq_bot_accounts::Entity)
                .from(Column::BotAccountId)
                .to(super::qq_bot_accounts::Column::BotAccountId)
                .into(),
        }
    }
}

impl Related<super::qq_agent_turns::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqAgentTurns.def()
    }
}

impl Related<super::qq_bot_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqBotAccounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
