//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "web_sources"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: u64,
    pub name: String,
    pub description: Option<String>,
    pub approval_status: String,
    pub trust_level: String,
    pub auto_publish: i8,
    pub allowed_domains: Option<Json>,
    pub default_language: String,
    pub enabled: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    Description,
    ApprovalStatus,
    TrustLevel,
    AutoPublish,
    AllowedDomains,
    DefaultLanguage,
    Enabled,
    CreatedAt,
    UpdatedAt,
    DeletedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    KnowledgeIngestionRuns,
    KnowledgePublishRecords,
    WebCrawlJobs,
    WebIngestionAuditLogs,
    WebPages,
    WebSourceUrls,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigUnsigned.def(),
            Self::Name => ColumnType::String(StringLen::N(128u32)).def(),
            Self::Description => ColumnType::Text.def().null(),
            Self::ApprovalStatus => ColumnType::String(StringLen::N(32u32)).def(),
            Self::TrustLevel => ColumnType::String(StringLen::N(32u32)).def(),
            Self::AutoPublish => ColumnType::TinyInteger.def(),
            Self::AllowedDomains => ColumnType::Json.def().null(),
            Self::DefaultLanguage => ColumnType::String(StringLen::N(16u32)).def(),
            Self::Enabled => ColumnType::TinyInteger.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::DeletedAt => ColumnType::DateTime.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::KnowledgeIngestionRuns => {
                Entity::has_many(super::knowledge_ingestion_runs::Entity).into()
            }
            Self::KnowledgePublishRecords => {
                Entity::has_many(super::knowledge_publish_records::Entity).into()
            }
            Self::WebCrawlJobs => Entity::has_many(super::web_crawl_jobs::Entity).into(),
            Self::WebIngestionAuditLogs => {
                Entity::has_many(super::web_ingestion_audit_logs::Entity).into()
            }
            Self::WebPages => Entity::has_many(super::web_pages::Entity).into(),
            Self::WebSourceUrls => Entity::has_many(super::web_source_urls::Entity).into(),
        }
    }
}

impl Related<super::knowledge_ingestion_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeIngestionRuns.def()
    }
}

impl Related<super::knowledge_publish_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgePublishRecords.def()
    }
}

impl Related<super::web_crawl_jobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebCrawlJobs.def()
    }
}

impl Related<super::web_ingestion_audit_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebIngestionAuditLogs.def()
    }
}

impl Related<super::web_pages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebPages.def()
    }
}

impl Related<super::web_source_urls::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebSourceUrls.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
