//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "agent_events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub event_id: u64,
    pub user_id: u64,
    pub conversation_id: Option<u64>,
    pub trace_id: Option<String>,
    pub turn_id: Option<String>,
    pub event_type: String,
    pub severity: String,
    pub tool_name: Option<String>,
    pub payload: Json,
    pub created_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "conversation_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub conversations: HasOne<super::conversations::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
