//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "community_posts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub post_id: u64,
    pub user_id: u64,
    pub title: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub extra_metadata: Option<Json>,
    pub likes_count: u32,
    pub comments_count: u32,
    pub status: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub community_comments: HasMany<super::community_comments::Entity>,
    #[sea_orm(has_many)]
    pub community_post_medias: HasMany<super::community_post_media::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
