//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "community_posts"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub post_id: u64,
    pub user_id: u64,
    pub title: Option<String>,
    pub content: String,
    pub extra_metadata: Option<Json>,
    pub likes_count: u32,
    pub comments_count: u32,
    pub status: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    PostId,
    UserId,
    Title,
    Content,
    ExtraMetadata,
    LikesCount,
    CommentsCount,
    Status,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    PostId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    CommunityComments,
    CommunityPostMedia,
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::PostId => ColumnType::BigUnsigned.def(),
            Self::UserId => ColumnType::BigUnsigned.def(),
            Self::Title => ColumnType::String(StringLen::N(150u32)).def().null(),
            Self::Content => ColumnType::Text.def(),
            Self::ExtraMetadata => ColumnType::Json.def().null(),
            Self::LikesCount => ColumnType::Unsigned.def(),
            Self::CommentsCount => ColumnType::Unsigned.def(),
            Self::Status => ColumnType::TinyInteger.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::CommunityComments => Entity::has_many(super::community_comments::Entity).into(),
            Self::CommunityPostMedia => {
                Entity::has_many(super::community_post_media::Entity).into()
            }
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::UserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::community_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommunityComments.def()
    }
}

impl Related<super::community_post_media::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommunityPostMedia.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
