//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "community_post_media")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub media_id: u64,
    pub post_id: u64,
    pub media_type: String,
    pub mime_type: String,
    #[sea_orm(ignore, column_type = "custom(\"longblob\")", select_as = "text")]
    pub media_data: String,
    pub created_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "post_id",
        to = "post_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub community_posts: HasOne<super::community_posts::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
