//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "conversations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique)]
    pub user_id: u64,
    pub title: Option<String>,
    pub message_count: u64,
    pub last_message_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub agent_events: HasMany<super::agent_events::Entity>,
    #[sea_orm(has_many)]
    pub conversation_messages: HasMany<super::conversation_messages::Entity>,
    #[sea_orm(has_many)]
    pub conversation_summaries: HasMany<super::conversation_summaries::Entity>,
    #[sea_orm(has_many)]
    pub post_conversation_risk_audits: HasMany<super::post_conversation_risk_audits::Entity>,
    #[sea_orm(has_many)]
    pub user_memories: HasMany<super::user_memories::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
