//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "conversation_messages")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub conversation_id: u64,
    pub sender_role: String,
    pub sender_user_id: Option<u64>,
    pub message_type: String,
    pub content: Json,
    pub token_count: Option<u32>,
    pub created_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "conversation_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub conversations: HasOne<super::conversations::Entity>,
    #[sea_orm(has_many)]
    pub user_memories: HasMany<super::user_memories::Entity>,
    #[sea_orm(has_many)]
    pub user_memory_evidences: HasMany<super::user_memory_evidence::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
