//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "depression_scales")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub scale_id: u16,
    #[sea_orm(unique)]
    pub scale_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub scale_description: Option<String>,
    pub min_score: i16,
    pub max_score: i16,
    pub severity_ranges: Json,
    pub questions: Json,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    #[sea_orm(has_many)]
    pub depression_assessments: HasMany<super::depression_assessments::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
