//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "fresh_topics")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique)]
    pub topic_key: String,
    pub title: String,
    #[sea_orm(
        ignore,
        column_type = "custom(\"MEDIUMTEXT\")",
        select_as = "text",
        nullable
    )]
    pub summary: Option<String>,
    pub entities: Option<Json>,
    pub first_seen_at: DateTime,
    pub last_seen_at: DateTime,
    #[sea_orm(column_type = "Double")]
    pub heat_score: f64,
    #[sea_orm(column_type = "Double")]
    pub freshness_score: f64,
    pub expires_at: DateTime,
    pub status: String,
    pub risk_flags: Option<Json>,
    pub metadata: Option<Json>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
    #[sea_orm(has_many)]
    pub fresh_chunks: HasMany<super::fresh_chunks::Entity>,
    #[sea_orm(has_many)]
    pub fresh_topic_evidences: HasMany<super::fresh_topic_evidence::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
