//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "fresh_topic_evidence"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub id: u64,
    pub topic_id: u64,
    pub item_id: u64,
    pub stance: String,
    pub confidence: f64,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    TopicId,
    ItemId,
    Stance,
    Confidence,
    CreatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    FreshItems,
    FreshTopics,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigUnsigned.def(),
            Self::TopicId => ColumnType::BigUnsigned.def(),
            Self::ItemId => ColumnType::BigUnsigned.def(),
            Self::Stance => ColumnType::String(StringLen::N(32u32)).def(),
            Self::Confidence => ColumnType::Double.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::FreshItems => Entity::belongs_to(super::fresh_items::Entity)
                .from(Column::ItemId)
                .to(super::fresh_items::Column::Id)
                .into(),
            Self::FreshTopics => Entity::belongs_to(super::fresh_topics::Entity)
                .from(Column::TopicId)
                .to(super::fresh_topics::Column::Id)
                .into(),
        }
    }
}

impl Related<super::fresh_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FreshItems.def()
    }
}

impl Related<super::fresh_topics::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FreshTopics.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
