//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "fresh_topic_evidence")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique_key = "uk_fresh_topic_evidence_pair")]
    pub topic_id: u64,
    #[sea_orm(unique_key = "uk_fresh_topic_evidence_pair")]
    pub item_id: u64,
    pub stance: String,
    #[sea_orm(column_type = "Double")]
    pub confidence: f64,
    pub created_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "item_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub fresh_items: BelongsTo<super::fresh_items::Entity>,
    #[sea_orm(
        belongs_to,
        from = "topic_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub fresh_topics: BelongsTo<super::fresh_topics::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
