//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "fresh_sources"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub id: u64,
    pub name: String,
    pub source_kind: String,
    pub base_url: Option<String>,
    pub allowed_domains: Option<Json>,
    pub trust_level: String,
    pub reliability_score: f64,
    pub crawl_interval_secs: u32,
    pub default_ttl_secs: u32,
    pub risk_policy: String,
    pub enabled: i8,
    pub metadata: Option<Json>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    SourceKind,
    BaseUrl,
    AllowedDomains,
    TrustLevel,
    ReliabilityScore,
    CrawlIntervalSecs,
    DefaultTtlSecs,
    RiskPolicy,
    Enabled,
    Metadata,
    CreatedAt,
    UpdatedAt,
    DeletedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    FreshItems,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigUnsigned.def(),
            Self::Name => ColumnType::String(StringLen::N(128u32)).def().unique(),
            Self::SourceKind => ColumnType::String(StringLen::N(32u32)).def(),
            Self::BaseUrl => ColumnType::Text.def().null(),
            Self::AllowedDomains => ColumnType::Json.def().null(),
            Self::TrustLevel => ColumnType::String(StringLen::N(32u32)).def(),
            Self::ReliabilityScore => ColumnType::Double.def(),
            Self::CrawlIntervalSecs => ColumnType::Unsigned.def(),
            Self::DefaultTtlSecs => ColumnType::Unsigned.def(),
            Self::RiskPolicy => ColumnType::String(StringLen::N(32u32)).def(),
            Self::Enabled => ColumnType::TinyInteger.def(),
            Self::Metadata => ColumnType::Json.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::DeletedAt => ColumnType::DateTime.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::FreshItems => Entity::has_many(super::fresh_items::Entity).into(),
        }
    }
}

impl Related<super::fresh_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FreshItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
