//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "knowledge_chunk_manifests")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub publish_record_id: u64,
    pub run_id: u64,
    pub document_id: u64,
    #[sea_orm(unique)]
    pub chunk_id: u64,
    #[sea_orm(unique_key = "uk_chunk_manifests_version_hash")]
    pub version_key: String,
    #[sea_orm(unique_key = "uk_chunk_manifests_version_hash")]
    pub chunk_hash: String,
    pub chunk_type: String,
    pub chunk_index: u32,
    pub active: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "chunk_id",
        to = "chunk_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub knowledge_chunks: HasOne<super::knowledge_chunks::Entity>,
    #[sea_orm(
        belongs_to,
        from = "document_id",
        to = "document_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub knowledge_documents: HasOne<super::knowledge_documents::Entity>,
    #[sea_orm(
        belongs_to,
        from = "run_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub knowledge_ingestion_runs: HasOne<super::knowledge_ingestion_runs::Entity>,
    #[sea_orm(
        belongs_to,
        from = "publish_record_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub knowledge_publish_records: HasOne<super::knowledge_publish_records::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
