//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "knowledge_vector_manifests"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: u64,
    pub publish_record_id: u64,
    pub run_id: u64,
    pub document_id: u64,
    pub chunk_id: u64,
    pub chunk_hash: String,
    pub vector_index_name: String,
    pub vector_point_id: String,
    pub embedding_provider: String,
    pub embedding_model: String,
    pub embedding_dimension: u32,
    pub active: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    PublishRecordId,
    RunId,
    DocumentId,
    ChunkId,
    ChunkHash,
    VectorIndexName,
    VectorPointId,
    EmbeddingProvider,
    EmbeddingModel,
    EmbeddingDimension,
    Active,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    KnowledgeChunks,
    KnowledgeDocuments,
    KnowledgeIngestionRuns,
    KnowledgePublishRecords,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigUnsigned.def(),
            Self::PublishRecordId => ColumnType::BigUnsigned.def(),
            Self::RunId => ColumnType::BigUnsigned.def(),
            Self::DocumentId => ColumnType::BigUnsigned.def(),
            Self::ChunkId => ColumnType::BigUnsigned.def(),
            Self::ChunkHash => ColumnType::Char(Some(64u32)).def(),
            Self::VectorIndexName => ColumnType::String(StringLen::N(128u32)).def(),
            Self::VectorPointId => ColumnType::Char(Some(64u32)).def(),
            Self::EmbeddingProvider => ColumnType::String(StringLen::N(64u32)).def(),
            Self::EmbeddingModel => ColumnType::String(StringLen::N(128u32)).def(),
            Self::EmbeddingDimension => ColumnType::Unsigned.def(),
            Self::Active => ColumnType::TinyInteger.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::KnowledgeChunks => Entity::belongs_to(super::knowledge_chunks::Entity)
                .from(Column::ChunkId)
                .to(super::knowledge_chunks::Column::ChunkId)
                .into(),
            Self::KnowledgeDocuments => Entity::belongs_to(super::knowledge_documents::Entity)
                .from(Column::DocumentId)
                .to(super::knowledge_documents::Column::DocumentId)
                .into(),
            Self::KnowledgeIngestionRuns => {
                Entity::belongs_to(super::knowledge_ingestion_runs::Entity)
                    .from(Column::RunId)
                    .to(super::knowledge_ingestion_runs::Column::Id)
                    .into()
            }
            Self::KnowledgePublishRecords => {
                Entity::belongs_to(super::knowledge_publish_records::Entity)
                    .from(Column::PublishRecordId)
                    .to(super::knowledge_publish_records::Column::Id)
                    .into()
            }
        }
    }
}

impl Related<super::knowledge_chunks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeChunks.def()
    }
}

impl Related<super::knowledge_documents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeDocuments.def()
    }
}

impl Related<super::knowledge_ingestion_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeIngestionRuns.def()
    }
}

impl Related<super::knowledge_publish_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgePublishRecords.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
