//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "knowledge_ingestion_runs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub source_id: u64,
    pub source_url_id: Option<u64>,
    pub crawl_job_id: Option<u64>,
    pub page_id: u64,
    pub content_hash: String,
    pub content_key: String,
    #[sea_orm(unique)]
    pub run_key: String,
    #[sea_orm(unique)]
    pub version_key: String,
    pub status: String,
    pub stage: String,
    pub llm_provider: Option<String>,
    pub llm_model: Option<String>,
    pub llm_prompt_version: Option<String>,
    pub llm_input_tokens: Option<u32>,
    pub llm_output_tokens: Option<u32>,
    pub chunker_version: Option<String>,
    pub embedding_provider: Option<String>,
    pub embedding_model: Option<String>,
    pub embedding_dimension: Option<u32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub quality_score: Option<f64>,
    pub quality_result: Option<Json>,
    pub risk_flags: Option<Json>,
    pub should_publish: Option<i8>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub retry_count: u32,
    pub started_at: Option<DateTime>,
    pub finished_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        ignore,
        column_type = "custom(\"MEDIUMTEXT\")",
        select_as = "text",
        nullable
    )]
    pub fetched_body_text: Option<String>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"MEDIUMTEXT\")",
        select_as = "text",
        nullable
    )]
    pub clean_text: Option<String>,
    pub distilled_json: Option<Json>,
    #[sea_orm(has_many)]
    pub knowledge_chunk_manifests: HasMany<super::knowledge_chunk_manifests::Entity>,
    #[sea_orm(has_many)]
    pub knowledge_publish_records: HasMany<super::knowledge_publish_records::Entity>,
    #[sea_orm(has_many)]
    pub knowledge_vector_manifests: HasMany<super::knowledge_vector_manifests::Entity>,
    #[sea_orm(
        belongs_to,
        from = "crawl_job_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub web_crawl_jobs: HasOne<super::web_crawl_jobs::Entity>,
    #[sea_orm(has_many)]
    pub web_ingestion_audit_logs: HasMany<super::web_ingestion_audit_logs::Entity>,
    #[sea_orm(
        belongs_to,
        from = "page_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub web_pages: HasOne<super::web_pages::Entity>,
    #[sea_orm(
        belongs_to,
        from = "source_url_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub web_source_urls: HasOne<super::web_source_urls::Entity>,
    #[sea_orm(
        belongs_to,
        from = "source_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub web_sources: HasOne<super::web_sources::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
