//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "psychology_categories")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub category_id: u16,
    #[sea_orm(unique)]
    pub category_name: String,
    pub parent_id: Option<u16>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub sort_order: i32,
    pub status: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub psychology_articles: HasMany<super::psychology_articles::Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "parent_id",
        to = "category_id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub psychology_categories: HasOne<Entity>,
    #[sea_orm(has_many)]
    pub psychology_qnas: HasMany<super::psychology_qna::Entity>,
    #[sea_orm(has_many)]
    pub psychology_resources: HasMany<super::psychology_resources::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
