//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "qq_agent_turns")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub turn_id: u64,
    pub bot_account_id: u64,
    pub qq_group_id: i64,
    pub trigger_message_id: u64,
    pub response_message_id: Option<u64>,
    pub trigger_type: String,
    pub qq_user_id: Option<i64>,
    pub internal_user_id: Option<u64>,
    pub prompt_version: Option<String>,
    pub model_name: Option<String>,
    pub reasoning_enabled: Option<i8>,
    pub input_token_count: Option<u32>,
    pub output_token_count: Option<u32>,
    pub latency_ms: Option<u32>,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    #[sea_orm(unique)]
    pub trace_id: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "bot_account_id",
        to = "bot_account_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub qq_bot_accounts: HasOne<super::qq_bot_accounts::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "QqGroupMessages2",
        from = "trigger_message_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub qq_group_messages_2: HasOne<super::qq_group_messages::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "QqGroupMessages1",
        from = "response_message_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub qq_group_messages_1: HasOne<super::qq_group_messages::Entity>,
    #[sea_orm(has_many)]
    pub qq_message_outboxes: HasMany<super::qq_message_outbox::Entity>,
    #[sea_orm(
        belongs_to,
        from = "internal_user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
