//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "qq_bot_accounts"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub bot_account_id: u64,
    pub platform: String,
    pub self_qq_id: i64,
    pub display_name: Option<String>,
    pub adapter: String,
    pub connection_mode: String,
    pub enabled: i8,
    pub config: Option<Json>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    BotAccountId,
    Platform,
    SelfQqId,
    DisplayName,
    Adapter,
    ConnectionMode,
    Enabled,
    Config,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    BotAccountId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    QqAgentTurns,
    QqGroupMessages,
    QqGroups,
    QqMessageOutbox,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::BotAccountId => ColumnType::BigUnsigned.def(),
            Self::Platform => ColumnType::String(StringLen::N(32u32)).def(),
            Self::SelfQqId => ColumnType::BigInteger.def().unique(),
            Self::DisplayName => ColumnType::String(StringLen::N(128u32)).def().null(),
            Self::Adapter => ColumnType::String(StringLen::N(64u32)).def(),
            Self::ConnectionMode => ColumnType::String(StringLen::N(32u32)).def(),
            Self::Enabled => ColumnType::TinyInteger.def(),
            Self::Config => ColumnType::Json.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::QqAgentTurns => Entity::has_many(super::qq_agent_turns::Entity).into(),
            Self::QqGroupMessages => Entity::has_many(super::qq_group_messages::Entity).into(),
            Self::QqGroups => Entity::has_many(super::qq_groups::Entity).into(),
            Self::QqMessageOutbox => Entity::has_many(super::qq_message_outbox::Entity).into(),
        }
    }
}

impl Related<super::qq_agent_turns::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqAgentTurns.def()
    }
}

impl Related<super::qq_group_messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqGroupMessages.def()
    }
}

impl Related<super::qq_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqGroups.def()
    }
}

impl Related<super::qq_message_outbox::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqMessageOutbox.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
