//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "qq_group_members"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub qq_group_id: i64,
    pub qq_user_id: i64,
    pub card: Option<String>,
    pub nickname: Option<String>,
    pub role: Option<String>,
    pub title: Option<String>,
    pub join_time: Option<i64>,
    pub last_seen_at: Option<i64>,
    pub status: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    QqGroupId,
    QqUserId,
    Card,
    Nickname,
    Role,
    Title,
    JoinTime,
    LastSeenAt,
    Status,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    QqGroupId,
    QqUserId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (i64, i64);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    QqExternalUsers,
    QqGroups,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::QqGroupId => ColumnType::BigInteger.def(),
            Self::QqUserId => ColumnType::BigInteger.def(),
            Self::Card => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::Nickname => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::Role => ColumnType::String(StringLen::N(10u32)).def().null(),
            Self::Title => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::JoinTime => ColumnType::BigInteger.def().null(),
            Self::LastSeenAt => ColumnType::BigInteger.def().null(),
            Self::Status => ColumnType::String(StringLen::N(10u32)).def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::QqExternalUsers => Entity::belongs_to(super::qq_external_users::Entity)
                .from(Column::QqUserId)
                .to(super::qq_external_users::Column::QqUserId)
                .into(),
            Self::QqGroups => Entity::belongs_to(super::qq_groups::Entity)
                .from(Column::QqGroupId)
                .to(super::qq_groups::Column::QqGroupId)
                .into(),
        }
    }
}

impl Related<super::qq_external_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqExternalUsers.def()
    }
}

impl Related<super::qq_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqGroups.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
