//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "qq_group_members")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub qq_group_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub qq_user_id: i64,
    pub card: Option<String>,
    pub nickname: Option<String>,
    pub role: Option<String>,
    pub title: Option<String>,
    pub join_time: Option<i64>,
    pub last_seen_at: Option<i64>,
    pub status: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "qq_user_id",
        to = "qq_user_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub qq_external_users: BelongsTo<super::qq_external_users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "qq_group_id",
        to = "qq_group_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub qq_groups: BelongsTo<super::qq_groups::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
