//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "qq_group_messages")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique_key = "uk_platform_message")]
    pub bot_account_id: u64,
    pub qq_group_id: i64,
    pub qq_user_id: Option<i64>,
    #[sea_orm(unique_key = "uk_platform_message")]
    pub platform_message_id: String,
    pub direction: String,
    #[sea_orm(column_type = "Text")]
    pub raw_text: String,
    #[sea_orm(column_type = "Text")]
    pub normalized_text: String,
    pub segments: Json,
    pub at_bot: i8,
    pub command_name: Option<String>,
    pub sent_at: i64,
    pub status: String,
    pub created_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "bot_account_id",
        to = "bot_account_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub qq_bot_accounts: BelongsTo<super::qq_bot_accounts::Entity>,
    #[sea_orm(
        belongs_to,
        from = "qq_user_id",
        to = "qq_user_id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub qq_external_users: BelongsTo<Option<super::qq_external_users::Entity>>,
    #[sea_orm(has_many)]
    pub qq_group_memories: HasMany<super::qq_group_memories::Entity>,
    #[sea_orm(
        belongs_to,
        from = "qq_group_id",
        to = "qq_group_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub qq_groups: BelongsTo<super::qq_groups::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
