//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "qq_group_summaries"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub summary_id: u64,
    pub qq_group_id: i64,
    pub summary_type: String,
    pub content: String,
    pub message_start_id: u64,
    pub message_end_id: u64,
    pub supersedes_id: Option<u64>,
    pub token_count: Option<u32>,
    pub status: i8,
    pub vector_id: Option<String>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    SummaryId,
    QqGroupId,
    SummaryType,
    Content,
    MessageStartId,
    MessageEndId,
    SupersedesId,
    TokenCount,
    Status,
    VectorId,
    CreatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    SummaryId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    SelfRef,
    QqGroups,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::SummaryId => ColumnType::BigUnsigned.def(),
            Self::QqGroupId => ColumnType::BigInteger.def(),
            Self::SummaryType => ColumnType::String(StringLen::N(30u32)).def(),
            Self::Content => ColumnType::Text.def(),
            Self::MessageStartId => ColumnType::BigUnsigned.def(),
            Self::MessageEndId => ColumnType::BigUnsigned.def(),
            Self::SupersedesId => ColumnType::BigUnsigned.def().null(),
            Self::TokenCount => ColumnType::Unsigned.def().null(),
            Self::Status => ColumnType::TinyInteger.def(),
            Self::VectorId => ColumnType::String(StringLen::N(64u32)).def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::SelfRef => Entity::belongs_to(Entity)
                .from(Column::SupersedesId)
                .to(Column::SummaryId)
                .into(),
            Self::QqGroups => Entity::belongs_to(super::qq_groups::Entity)
                .from(Column::QqGroupId)
                .to(super::qq_groups::Column::QqGroupId)
                .into(),
        }
    }
}

impl Related<super::qq_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqGroups.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
