//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "qq_group_memories")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub group_memory_id: u64,
    pub qq_group_id: i64,
    pub memory_key: Option<String>,
    pub canonical_form: Option<String>,
    pub memory_type: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[sea_orm(column_type = "Double")]
    pub confidence: f64,
    #[sea_orm(column_type = "Double")]
    pub salience: f64,
    pub source_message_id: Option<u64>,
    pub reinforce_count: u32,
    pub status: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "source_message_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub qq_group_messages: HasOne<super::qq_group_messages::Entity>,
    #[sea_orm(
        belongs_to,
        from = "qq_group_id",
        to = "qq_group_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub qq_groups: HasOne<super::qq_groups::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
