//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "qq_message_outbox")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub outbox_id: u64,
    pub bot_account_id: u64,
    pub qq_group_id: Option<i64>,
    pub qq_user_id: Option<i64>,
    pub target_type: String,
    pub payload: Json,
    pub related_turn_id: Option<u64>,
    pub status: String,
    pub attempts: u32,
    pub max_attempts: u32,
    pub next_run_at: i64,
    pub platform_message_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "related_turn_id",
        to = "turn_id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub qq_agent_turns: HasOne<super::qq_agent_turns::Entity>,
    #[sea_orm(
        belongs_to,
        from = "bot_account_id",
        to = "bot_account_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub qq_bot_accounts: HasOne<super::qq_bot_accounts::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
