//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "qq_relationships")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique_key = "uk_group_user")]
    pub qq_group_id: i64,
    #[sea_orm(unique_key = "uk_group_user")]
    pub qq_user_id: i64,
    #[sea_orm(column_type = "Float")]
    pub familiarity: f32,
    pub interaction_count: u32,
    pub last_interaction_at: Option<i64>,
    pub rapport: String,
    pub nickname_preference: Option<String>,
    pub known_interests: Option<Json>,
    pub known_avoid_topics: Option<Json>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "qq_user_id",
        to = "qq_user_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub qq_external_users: BelongsTo<super::qq_external_users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
