//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "qq_relationships"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub id: u64,
    pub qq_group_id: i64,
    pub qq_user_id: i64,
    pub familiarity: f32,
    pub interaction_count: u32,
    pub last_interaction_at: Option<i64>,
    pub rapport: String,
    pub nickname_preference: Option<String>,
    pub known_interests: Option<Json>,
    pub known_avoid_topics: Option<Json>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    QqGroupId,
    QqUserId,
    Familiarity,
    InteractionCount,
    LastInteractionAt,
    Rapport,
    NicknamePreference,
    KnownInterests,
    KnownAvoidTopics,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    QqExternalUsers,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigUnsigned.def(),
            Self::QqGroupId => ColumnType::BigInteger.def(),
            Self::QqUserId => ColumnType::BigInteger.def(),
            Self::Familiarity => ColumnType::Float.def(),
            Self::InteractionCount => ColumnType::Unsigned.def(),
            Self::LastInteractionAt => ColumnType::BigInteger.def().null(),
            Self::Rapport => ColumnType::String(StringLen::N(32u32)).def(),
            Self::NicknamePreference => ColumnType::String(StringLen::N(64u32)).def().null(),
            Self::KnownInterests => ColumnType::Json.def().null(),
            Self::KnownAvoidTopics => ColumnType::Json.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::QqExternalUsers => Entity::belongs_to(super::qq_external_users::Entity)
                .from(Column::QqUserId)
                .to(super::qq_external_users::Column::QqUserId)
                .into(),
        }
    }
}

impl Related<super::qq_external_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QqExternalUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
