//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "qq_user_profiles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub qq_user_id: i64,
    pub interest_tags: Option<Json>,
    pub active_hours: Option<Json>,
    pub speaking_style: Option<String>,
    pub topic_frequency: Option<Json>,
    pub total_messages: u32,
    #[sea_orm(column_type = "Double")]
    pub avg_message_length: f64,
    #[sea_orm(column_type = "Double")]
    pub emoji_usage_rate: f64,
    pub first_seen_at: Option<i64>,
    pub last_summary_at: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub raw_profile: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "qq_user_id",
        to = "qq_user_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub qq_external_users: BelongsTo<super::qq_external_users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
