//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "stored_objects")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub object_id: u64,
    #[sea_orm(unique_key = "uk_stored_objects_bucket_key")]
    pub bucket: String,
    #[sea_orm(unique_key = "uk_stored_objects_bucket_key")]
    pub object_key: String,
    pub original_name: String,
    pub mime_type: String,
    pub size_bytes: u64,
    pub sha256: String,
    pub storage_backend: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub public_url: Option<String>,
    pub created_by: Option<u64>,
    pub created_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "created_by",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
