//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_memory_evidence")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub evidence_id: u64,
    #[sea_orm(unique_key = "uk_memory_source_type")]
    pub memory_id: u64,
    #[sea_orm(unique_key = "uk_memory_source_type")]
    pub source_type: String,
    #[sea_orm(unique_key = "uk_memory_source_type")]
    pub source_ref_id: u64,
    pub message_id: Option<u64>,
    pub summary_id: Option<u64>,
    pub source_deleted: i8,
    #[sea_orm(unique_key = "uk_memory_source_type")]
    pub evidence_type: String,
    #[sea_orm(column_type = "Decimal(Some((4, 3)))", nullable)]
    pub confidence: Option<Decimal>,
    pub extractor_version: Option<String>,
    pub created_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "message_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub conversation_messages: HasOne<super::conversation_messages::Entity>,
    #[sea_orm(
        belongs_to,
        from = "summary_id",
        to = "summary_id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub conversation_summaries: HasOne<super::conversation_summaries::Entity>,
    #[sea_orm(
        belongs_to,
        from = "memory_id",
        to = "memory_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub user_memories: HasOne<super::user_memories::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
