//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "user_persona_snapshots"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub snapshot_id: u64,
    pub user_id: u64,
    pub status: String,
    pub active_marker: Option<i8>,
    pub snapshot_data: Json,
    pub source_memory_ids: Json,
    pub source_summary_ids: Option<Json>,
    pub source_recent_message_ids: Option<Json>,
    pub input_hash: String,
    pub model_name: String,
    pub prompt_version: String,
    pub schema_version: String,
    pub generation_ms: u32,
    pub supersedes_id: Option<u64>,
    pub error_message: Option<String>,
    pub created_at: DateTime,
    pub expires_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    SnapshotId,
    UserId,
    Status,
    ActiveMarker,
    SnapshotData,
    SourceMemoryIds,
    SourceSummaryIds,
    SourceRecentMessageIds,
    InputHash,
    ModelName,
    PromptVersion,
    SchemaVersion,
    GenerationMs,
    SupersedesId,
    ErrorMessage,
    CreatedAt,
    ExpiresAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    SnapshotId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = u64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    SelfRef,
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::SnapshotId => ColumnType::BigUnsigned.def(),
            Self::UserId => ColumnType::BigUnsigned.def(),
            Self::Status => ColumnType::String(StringLen::N(32u32)).def(),
            Self::ActiveMarker => ColumnType::TinyInteger.def().null(),
            Self::SnapshotData => ColumnType::Json.def(),
            Self::SourceMemoryIds => ColumnType::Json.def(),
            Self::SourceSummaryIds => ColumnType::Json.def().null(),
            Self::SourceRecentMessageIds => ColumnType::Json.def().null(),
            Self::InputHash => ColumnType::Char(Some(64u32)).def(),
            Self::ModelName => ColumnType::String(StringLen::N(128u32)).def(),
            Self::PromptVersion => ColumnType::String(StringLen::N(64u32)).def(),
            Self::SchemaVersion => ColumnType::String(StringLen::N(64u32)).def(),
            Self::GenerationMs => ColumnType::Unsigned.def(),
            Self::SupersedesId => ColumnType::BigUnsigned.def().null(),
            Self::ErrorMessage => ColumnType::Text.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::ExpiresAt => ColumnType::DateTime.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::SelfRef => Entity::belongs_to(Entity)
                .from(Column::SupersedesId)
                .to(Column::SnapshotId)
                .into(),
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::UserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
