//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_persona_snapshots")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub snapshot_id: u64,
    #[sea_orm(unique_key = "uk_active_persona_user")]
    pub user_id: u64,
    pub status: String,
    pub snapshot_data: Json,
    pub source_memory_ids: Json,
    pub source_summary_ids: Option<Json>,
    pub source_recent_message_ids: Option<Json>,
    pub input_hash: String,
    pub model_name: String,
    pub prompt_version: String,
    pub schema_version: String,
    pub generation_ms: u32,
    pub supersedes_id: Option<u64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub created_at: DateTime,
    pub expires_at: Option<DateTime>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "supersedes_id",
        to = "snapshot_id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub user_persona_snapshots: HasOne<Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
