//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "web_crawl_jobs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub source_id: Option<u64>,
    pub status: String,
    pub scheduled_at: DateTime,
    pub started_at: Option<DateTime>,
    pub finished_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub knowledge_ingestion_runs: HasMany<super::knowledge_ingestion_runs::Entity>,
    #[sea_orm(
        belongs_to,
        from = "source_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub web_sources: HasOne<super::web_sources::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
