//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "web_source_urls")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique_key = "uk_web_source_urls_source_hash")]
    pub source_id: u64,
    #[sea_orm(column_type = "Text")]
    pub url: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub canonical_url: Option<String>,
    #[sea_orm(unique_key = "uk_web_source_urls_source_hash")]
    pub url_hash: String,
    pub enabled: i8,
    pub crawl_interval_secs: u32,
    pub last_crawled_at: Option<DateTime>,
    pub last_content_hash: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
    #[sea_orm(has_many)]
    pub knowledge_ingestion_runs: HasMany<super::knowledge_ingestion_runs::Entity>,
    #[sea_orm(has_many)]
    pub web_ingestion_audit_logs: HasMany<super::web_ingestion_audit_logs::Entity>,
    #[sea_orm(has_many)]
    pub web_pages: HasMany<super::web_pages::Entity>,
    #[sea_orm(
        belongs_to,
        from = "source_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub web_sources: HasOne<super::web_sources::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
