//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "web_pages")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique_key = "uk_web_pages_source_hash")]
    pub source_id: u64,
    pub source_url_id: Option<u64>,
    #[sea_orm(column_type = "Text")]
    pub url: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub canonical_url: Option<String>,
    #[sea_orm(unique_key = "uk_web_pages_source_hash")]
    pub url_hash: String,
    pub latest_content_hash: Option<String>,
    pub latest_success_run_id: Option<u64>,
    pub last_fetched_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
    #[sea_orm(has_many)]
    pub knowledge_ingestion_runs: HasMany<super::knowledge_ingestion_runs::Entity>,
    #[sea_orm(has_many)]
    pub knowledge_publish_records: HasMany<super::knowledge_publish_records::Entity>,
    #[sea_orm(has_many)]
    pub web_ingestion_audit_logs: HasMany<super::web_ingestion_audit_logs::Entity>,
    #[sea_orm(
        belongs_to,
        from = "source_url_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub web_source_urls: HasOne<super::web_source_urls::Entity>,
    #[sea_orm(
        belongs_to,
        from = "source_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub web_sources: HasOne<super::web_sources::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
