//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "qq_bot_accounts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub bot_account_id: u64,
    pub platform: String,
    #[sea_orm(unique)]
    pub self_qq_id: i64,
    pub display_name: Option<String>,
    pub adapter: String,
    pub connection_mode: String,
    pub enabled: i8,
    pub config: Option<Json>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub qq_agent_turns: HasMany<super::qq_agent_turns::Entity>,
    #[sea_orm(has_many)]
    pub qq_group_messages: HasMany<super::qq_group_messages::Entity>,
    #[sea_orm(has_many)]
    pub qq_groups: HasMany<super::qq_groups::Entity>,
    #[sea_orm(has_many)]
    pub qq_message_outboxes: HasMany<super::qq_message_outbox::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
