//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "qq_external_users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub qq_user_id: i64,
    pub internal_user_id: Option<u64>,
    pub nickname: Option<String>,
    pub avatar_url: Option<String>,
    pub last_seen_at: Option<i64>,
    pub memory_enabled: i8,
    pub persona_enabled: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub qq_group_messages: HasMany<super::qq_group_messages::Entity>,
    #[sea_orm(has_many)]
    pub qq_relationships: HasMany<super::qq_relationships::Entity>,
    #[sea_orm(has_one)]
    pub qq_user_profiles: HasOne<super::qq_user_profiles::Entity>,
    #[sea_orm(has_many, via = "qq_group_members")]
    pub qq_groups: HasMany<super::qq_groups::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
