//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "qq_group_summaries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub summary_id: u64,
    pub qq_group_id: i64,
    pub summary_type: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub message_start_id: u64,
    pub message_end_id: u64,
    pub supersedes_id: Option<u64>,
    pub token_count: Option<u32>,
    pub status: i8,
    pub vector_id: Option<String>,
    pub created_at: DateTime,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "supersedes_id",
        to = "summary_id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub qq_group_summaries: BelongsTo<Option<Entity>>,
    #[sea_orm(
        belongs_to,
        from = "qq_group_id",
        to = "qq_group_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub qq_groups: BelongsTo<super::qq_groups::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
