//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "qq_groups")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub qq_group_id: i64,
    pub group_name: Option<String>,
    pub bot_account_id: u64,
    pub enabled: i8,
    pub trigger_policy: String,
    pub cooldown_secs: u64,
    pub max_segments: u32,
    pub max_chars_per_segment: u32,
    pub allow_proactive: i8,
    pub keywords: Option<Json>,
    pub memory_policy: String,
    pub last_seen_at: Option<i64>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "bot_account_id",
        to = "bot_account_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub qq_bot_accounts: BelongsTo<super::qq_bot_accounts::Entity>,
    #[sea_orm(has_many)]
    pub qq_group_memories: HasMany<super::qq_group_memories::Entity>,
    #[sea_orm(has_many)]
    pub qq_group_messages: HasMany<super::qq_group_messages::Entity>,
    #[sea_orm(has_many)]
    pub qq_group_summaries: HasMany<super::qq_group_summaries::Entity>,
    #[sea_orm(has_many, via = "qq_group_members")]
    pub qq_external_users: HasMany<super::qq_external_users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
