//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "community_comments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub comment_id: u64,
    pub post_id: u64,
    pub user_id: u64,
    pub parent_comment_id: Option<u64>,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub attachments: Option<Json>,
    pub likes_count: u32,
    pub status: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "parent_comment_id",
        to = "comment_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub community_comments: BelongsTo<Option<Entity>>,
    #[sea_orm(
        belongs_to,
        from = "post_id",
        to = "post_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub community_posts: BelongsTo<super::community_posts::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
