//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "content_likes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub like_id: u64,
    #[sea_orm(unique_key = "uk_content_likes_user_content")]
    pub user_id: u64,
    #[sea_orm(unique_key = "uk_content_likes_user_content")]
    pub content_type: String,
    #[sea_orm(unique_key = "uk_content_likes_user_content")]
    pub content_id: u64,
    pub created_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
