//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "conversation_summaries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub summary_id: u64,
    pub conversation_id: u64,
    pub user_id: u64,
    pub summary_type: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub message_start_id: u64,
    pub message_end_id: u64,
    pub supersedes_id: Option<u64>,
    pub token_count: Option<u32>,
    pub vector_id: Option<String>,
    pub embedding_provider: Option<String>,
    pub embedding_model: Option<String>,
    pub embedding_dimension: Option<u32>,
    pub indexed_at: Option<DateTime>,
    pub status: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "supersedes_id",
        to = "summary_id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub conversation_summaries: BelongsTo<Option<Entity>>,
    #[sea_orm(
        belongs_to,
        from = "conversation_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub conversations: BelongsTo<super::conversations::Entity>,
    #[sea_orm(has_many)]
    pub user_memory_evidences: HasMany<super::user_memory_evidence::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
