//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "domain_event_outbox")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique)]
    pub event_key: String,
    pub event_type: String,
    pub aggregate_type: String,
    pub aggregate_id: u64,
    pub payload: Json,
    pub status: String,
    pub retry_count: u32,
    pub max_retries: u32,
    pub next_retry_at: Option<DateTime>,
    pub locked_by: Option<String>,
    pub locked_until: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub published_at: Option<DateTime>,
}

impl ActiveModelBehavior for ActiveModel {}
