//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "fresh_chunks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique_key = "uk_fresh_chunks_item_idx")]
    pub item_id: u64,
    pub topic_id: Option<u64>,
    #[sea_orm(unique_key = "uk_fresh_chunks_item_idx")]
    pub chunk_index: u32,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub content_hash: String,
    pub token_count: Option<u32>,
    pub metadata: Option<Json>,
    #[sea_orm(unique)]
    pub vector_id: Option<String>,
    pub embedding_provider: Option<String>,
    pub embedding_model: Option<String>,
    pub embedding_dimension: Option<u32>,
    pub active: i8,
    pub indexed_at: Option<DateTime>,
    pub expires_at: DateTime,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "item_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub fresh_items: BelongsTo<super::fresh_items::Entity>,
    #[sea_orm(
        belongs_to,
        from = "topic_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub fresh_topics: BelongsTo<Option<super::fresh_topics::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
