//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "fresh_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique_key = "uk_fresh_items_source_url_hash")]
    pub source_id: u64,
    #[sea_orm(column_type = "Text", nullable)]
    pub url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub canonical_url: Option<String>,
    #[sea_orm(unique_key = "uk_fresh_items_source_url_hash")]
    pub url_hash: Option<String>,
    pub title: Option<String>,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")", select_as = "text", nullable)]
    pub raw_text: Option<String>,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")", select_as = "text", nullable)]
    pub clean_text: Option<String>,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")", select_as = "text", nullable)]
    pub summary: Option<String>,
    pub published_at: Option<DateTime>,
    pub fetched_at: DateTime,
    pub expires_at: DateTime,
    #[sea_orm(unique_key = "uk_fresh_items_source_content")]
    pub content_hash: String,
    pub status: String,
    #[sea_orm(column_type = "Double")]
    pub reliability_score: f64,
    #[sea_orm(column_type = "Double")]
    pub freshness_score: f64,
    #[sea_orm(column_type = "Double")]
    pub heat_score: f64,
    pub rumor_level: String,
    pub risk_flags: Option<Json>,
    pub metadata: Option<Json>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
    #[sea_orm(has_many)]
    pub fresh_chunks: HasMany<super::fresh_chunks::Entity>,
    #[sea_orm(
        belongs_to,
        from = "source_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub fresh_sources: BelongsTo<super::fresh_sources::Entity>,
    #[sea_orm(has_many)]
    pub fresh_topic_evidences: HasMany<super::fresh_topic_evidence::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
