//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "fresh_sources")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique)]
    pub name: String,
    pub source_kind: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub base_url: Option<String>,
    pub allowed_domains: Option<Json>,
    pub trust_level: String,
    #[sea_orm(column_type = "Double")]
    pub reliability_score: f64,
    pub crawl_interval_secs: u32,
    pub default_ttl_secs: u32,
    pub risk_policy: String,
    pub enabled: i8,
    pub metadata: Option<Json>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
    #[sea_orm(has_many)]
    pub fresh_items: HasMany<super::fresh_items::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
