//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "knowledge_publish_records")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub source_id: u64,
    pub page_id: u64,
    pub run_id: u64,
    pub document_id: u64,
    pub version_key: String,
    pub content_hash: String,
    pub publish_status: String,
    pub active: i8,
    #[sea_orm(unique)]
    pub active_page_key: Option<String>,
    pub activated_at: Option<DateTime>,
    pub superseded_at: Option<DateTime>,
    pub superseded_by_record_id: Option<u64>,
    pub rolled_back_from_record_id: Option<u64>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub knowledge_chunk_manifests: HasMany<super::knowledge_chunk_manifests::Entity>,
    #[sea_orm(
        belongs_to,
        from = "document_id",
        to = "document_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub knowledge_documents: BelongsTo<super::knowledge_documents::Entity>,
    #[sea_orm(
        belongs_to,
        from = "run_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub knowledge_ingestion_runs: BelongsTo<super::knowledge_ingestion_runs::Entity>,
    #[sea_orm(has_many)]
    pub knowledge_vector_manifests: HasMany<super::knowledge_vector_manifests::Entity>,
    #[sea_orm(has_many)]
    pub web_ingestion_audit_logs: HasMany<super::web_ingestion_audit_logs::Entity>,
    #[sea_orm(
        belongs_to,
        from = "page_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub web_pages: BelongsTo<super::web_pages::Entity>,
    #[sea_orm(
        belongs_to,
        from = "source_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub web_sources: BelongsTo<super::web_sources::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
