//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "knowledge_embeddings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub embedding_id: u64,
    #[sea_orm(unique_key = "uk_knowledge_embeddings_chunk_model")]
    pub chunk_id: u64,
    #[sea_orm(unique_key = "uk_knowledge_embeddings_chunk_model")]
    pub provider: String,
    #[sea_orm(unique_key = "uk_knowledge_embeddings_chunk_model")]
    pub model: String,
    pub dimension: u32,
    pub embedding_json: Json,
    pub created_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "chunk_id",
        to = "chunk_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub knowledge_chunks: BelongsTo<super::knowledge_chunks::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
