//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "knowledge_documents")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub document_id: u64,
    #[sea_orm(unique_key = "uk_knowledge_documents_source")]
    pub source_type: String,
    #[sea_orm(unique_key = "uk_knowledge_documents_source")]
    pub source_id: Option<u64>,
    pub owner_user_id: Option<u64>,
    pub visibility: String,
    pub title: Option<String>,
    pub content_hash: String,
    pub source_version: Option<String>,
    pub source_updated_at: Option<DateTime>,
    pub metadata: Option<Json>,
    pub status: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
    #[sea_orm(has_many)]
    pub knowledge_chunk_manifests: HasMany<super::knowledge_chunk_manifests::Entity>,
    #[sea_orm(has_many)]
    pub knowledge_chunks: HasMany<super::knowledge_chunks::Entity>,
    #[sea_orm(has_many)]
    pub knowledge_publish_records: HasMany<super::knowledge_publish_records::Entity>,
    #[sea_orm(has_many)]
    pub knowledge_vector_manifests: HasMany<super::knowledge_vector_manifests::Entity>,
    #[sea_orm(
        belongs_to,
        from = "owner_user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users: BelongsTo<Option<super::users::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
