//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "knowledge_chunks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub chunk_id: u64,
    #[sea_orm(unique_key = "uk_knowledge_chunks_doc_idx")]
    pub document_id: u64,
    #[sea_orm(unique_key = "uk_knowledge_chunks_doc_idx")]
    pub chunk_index: u32,
    pub char_start: Option<u32>,
    pub char_end: Option<u32>,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub content_hash: Option<String>,
    pub token_count: Option<u32>,
    pub metadata: Option<Json>,
    pub status: i8,
    pub created_at: DateTime,
    #[sea_orm(unique)]
    pub vector_id: Option<String>,
    pub embedding_provider: Option<String>,
    pub embedding_model: Option<String>,
    pub embedding_dimension: Option<u32>,
    pub indexed_at: Option<DateTime>,
    #[sea_orm(has_one)]
    pub knowledge_chunk_manifests: HasOne<super::knowledge_chunk_manifests::Entity>,
    #[sea_orm(
        belongs_to,
        from = "document_id",
        to = "document_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub knowledge_documents: BelongsTo<super::knowledge_documents::Entity>,
    #[sea_orm(has_many)]
    pub knowledge_embeddings: HasMany<super::knowledge_embeddings::Entity>,
    #[sea_orm(has_many)]
    pub knowledge_vector_manifests: HasMany<super::knowledge_vector_manifests::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
