//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "post_conversation_risk_audits")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub audit_id: u64,
    pub user_id: u64,
    pub conversation_id: u64,
    pub audit_scope: String,
    pub user_message_ref_id: Option<u64>,
    pub assistant_message_ref_id: Option<u64>,
    pub user_message_id: Option<u64>,
    pub assistant_message_id: Option<u64>,
    pub status: String,
    pub risk_level: Option<String>,
    pub risk_categories: Option<Json>,
    #[sea_orm(column_type = "Decimal(Some((4, 3)))", nullable)]
    pub confidence: Option<Decimal>,
    pub input_hash: Option<String>,
    pub detector_name: Option<String>,
    pub detector_version: Option<String>,
    pub model_name: Option<String>,
    pub checked_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub metadata: Option<Json>,
    pub source_deleted: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        relation_enum = "ConversationMessages2",
        from = "user_message_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub conversation_messages_2: BelongsTo<Option<super::conversation_messages::Entity>>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ConversationMessages1",
        from = "assistant_message_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub conversation_messages_1: BelongsTo<Option<super::conversation_messages::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "conversation_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub conversations: BelongsTo<super::conversations::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
