//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "psychology_resources")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub resource_id: u64,
    pub category_id: u16,
    pub resource_type: String,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "custom(\"longblob\")", select_as = "text", nullable)]
    pub file_data: Option<String>,
    pub external_url: Option<String>,
    pub file_size: Option<u64>,
    pub mime_type: Option<String>,
    pub duration: Option<u32>,
    #[sea_orm(column_type = "Binary(255)", nullable)]
    pub thumbnail: Option<Vec<u8>>,
    pub tags: Option<Json>,
    pub view_count: u32,
    pub like_count: u32,
    pub status: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "category_id",
        to = "category_id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub psychology_categories: BelongsTo<super::psychology_categories::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
