//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "psychology_qna")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub qna_id: u64,
    pub category_id: u16,
    #[sea_orm(column_type = "Text")]
    pub question: String,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")", select_as = "text")]
    pub answer: String,
    pub expert_name: Option<String>,
    pub expert_title: Option<String>,
    pub tags: Option<Json>,
    pub view_count: u32,
    pub like_count: u32,
    pub is_verified: i8,
    pub status: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "category_id",
        to = "category_id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub psychology_categories: BelongsTo<super::psychology_categories::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
