//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "psychology_articles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub article_id: u64,
    pub category_id: u16,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub summary: Option<String>,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")", select_as = "text")]
    pub content: String,
    pub author: Option<String>,
    pub source: Option<String>,
    pub tags: Option<Json>,
    #[sea_orm(column_type = "Binary(255)", nullable)]
    pub cover_image: Option<Vec<u8>>,
    pub view_count: u32,
    pub like_count: u32,
    pub is_featured: i8,
    pub is_published: i8,
    pub publish_date: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "category_id",
        to = "category_id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub psychology_categories: BelongsTo<super::psychology_categories::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
