//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "user_memories")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub memory_id: u64,
    #[sea_orm(unique_key = "uk_user_memory_key")]
    pub user_id: u64,
    #[sea_orm(unique_key = "uk_user_memory_key")]
    pub memory_key: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub canonical_form: Option<String>,
    pub memory_type: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[sea_orm(column_type = "Decimal(Some((3, 2)))")]
    pub source_confidence: Decimal,
    #[sea_orm(column_type = "Double")]
    pub confidence: f64,
    #[sea_orm(column_type = "Double")]
    pub salience: f64,
    pub source_conversation_id: Option<u64>,
    pub source_message_id: Option<u64>,
    pub reinforced_at: Option<DateTime>,
    pub reinforce_count: u32,
    pub contradicted_at: Option<DateTime>,
    pub superseded_by: Option<u64>,
    pub status: i8,
    pub canonicalizer_version: Option<String>,
    pub merge_decision: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub merge_reason: Option<String>,
    pub metadata: Option<Json>,
    pub last_accessed_at: Option<DateTime>,
    pub access_count: u32,
    #[sea_orm(unique)]
    pub vector_id: Option<String>,
    pub embedding_provider: Option<String>,
    pub embedding_model: Option<String>,
    pub embedding_dimension: Option<u32>,
    pub indexed_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "source_message_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub conversation_messages: BelongsTo<Option<super::conversation_messages::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "source_conversation_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub conversations: BelongsTo<Option<super::conversations::Entity>>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "superseded_by",
        to = "memory_id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub user_memories: BelongsTo<Option<Entity>>,
    #[sea_orm(has_many)]
    pub user_memory_evidences: HasMany<super::user_memory_evidence::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
