//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique)]
    pub username: String,
    pub password: String,
    #[sea_orm(unique)]
    pub email: Option<String>,
    #[sea_orm(unique)]
    pub phone: Option<String>,
    #[sea_orm(column_type = "Binary(255)", nullable)]
    pub avatar: Option<Vec<u8>>,
    pub nickname: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub last_login_at: Option<DateTime>,
    pub status: i8,
    pub role: String,
    #[sea_orm(has_many)]
    pub agent_events: HasMany<super::agent_events::Entity>,
    #[sea_orm(has_many)]
    pub community_comments: HasMany<super::community_comments::Entity>,
    #[sea_orm(has_many)]
    pub community_posts: HasMany<super::community_posts::Entity>,
    #[sea_orm(has_many)]
    pub content_likes: HasMany<super::content_likes::Entity>,
    #[sea_orm(has_many)]
    pub conversation_summaries: HasMany<super::conversation_summaries::Entity>,
    #[sea_orm(has_one)]
    pub conversations: HasOne<super::conversations::Entity>,
    #[sea_orm(has_many)]
    pub depression_assessments: HasMany<super::depression_assessments::Entity>,
    #[sea_orm(has_many)]
    pub knowledge_documents: HasMany<super::knowledge_documents::Entity>,
    #[sea_orm(has_many)]
    pub post_conversation_risk_audits: HasMany<super::post_conversation_risk_audits::Entity>,
    #[sea_orm(has_many)]
    pub refresh_tokens: HasMany<super::refresh_tokens::Entity>,
    #[sea_orm(has_many)]
    pub stored_objects: HasMany<super::stored_objects::Entity>,
    #[sea_orm(has_one)]
    pub user_context_versions: HasOne<super::user_context_versions::Entity>,
    #[sea_orm(has_many)]
    pub user_diaries: HasMany<super::user_diaries::Entity>,
    #[sea_orm(has_many)]
    pub user_knowledge_favorites: HasMany<super::user_knowledge_favorites::Entity>,
    #[sea_orm(has_many)]
    pub user_memories: HasMany<super::user_memories::Entity>,
    #[sea_orm(has_many)]
    pub user_persona_snapshots: HasMany<super::user_persona_snapshots::Entity>,
    #[sea_orm(has_one)]
    pub user_profiles: HasOne<super::user_profiles::Entity>,
    #[sea_orm(has_many)]
    pub vector_index_records: HasMany<super::vector_index_records::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
