//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "web_ingestion_audit_logs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub source_id: Option<u64>,
    pub source_url_id: Option<u64>,
    pub page_id: Option<u64>,
    pub run_id: Option<u64>,
    pub publish_record_id: Option<u64>,
    pub action: String,
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    pub metadata: Option<Json>,
    pub created_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "run_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub knowledge_ingestion_runs: BelongsTo<Option<super::knowledge_ingestion_runs::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "publish_record_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub knowledge_publish_records: BelongsTo<Option<super::knowledge_publish_records::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "page_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub web_pages: BelongsTo<Option<super::web_pages::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "source_url_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub web_source_urls: BelongsTo<Option<super::web_source_urls::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "source_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub web_sources: BelongsTo<Option<super::web_sources::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
