//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "web_sources")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub approval_status: String,
    pub trust_level: String,
    pub auto_publish: i8,
    pub allowed_domains: Option<Json>,
    pub default_language: String,
    pub enabled: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
    #[sea_orm(has_many)]
    pub knowledge_ingestion_runs: HasMany<super::knowledge_ingestion_runs::Entity>,
    #[sea_orm(has_many)]
    pub knowledge_publish_records: HasMany<super::knowledge_publish_records::Entity>,
    #[sea_orm(has_many)]
    pub web_crawl_jobs: HasMany<super::web_crawl_jobs::Entity>,
    #[sea_orm(has_many)]
    pub web_ingestion_audit_logs: HasMany<super::web_ingestion_audit_logs::Entity>,
    #[sea_orm(has_many)]
    pub web_pages: HasMany<super::web_pages::Entity>,
    #[sea_orm(has_many)]
    pub web_source_urls: HasMany<super::web_source_urls::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
